import { DwgPoint3D } from 'database/common'

import { DwgEntity } from '../entities'
import { DwgCommonTableEntry } from './table'

export interface DwgBlockRecordTableEntry extends DwgCommonTableEntry {
  /**
   * Block name
   */
  name: string
  /**
   * Block-type flags (bit-coded values, may be combined):
   * - 0: Indicates none of the following flags apply
   * - 1: This is an anonymous block generated by hatching, associative dimensioning, other internal operations, or an application
   * - 2: This block has non-constant attribute definitions (this bit is not set if the block has any attribute definitions that are constant, or has no attribute definitions at all)
   * - 4: This block is an external reference (xref)
   * - 8: This block is an xref overlay
   * - 16: This block is externally dependent
   * - 32: This is a resolved external reference, or dependent of an external reference (ignored on input)
   * - 64: This definition is a referenced external reference (ignored on input)
   */
  flags: number
  /**
   * Base point
   */
  basePoint: DwgPoint3D
  /**
   * Block description (optional)
   */
  description?: string
  /**
   * Hard-pointer ID/handle to associated LAYOUT object
   */
  layout: number
  /**
   * Block insertion units.
   */
  insertionUnits: number
  /**
   * Block explodability
   */
  explodability: number
  /**
   * Block scalability
   */
  scalability: number
  /**
   * Binary data for bitmap preview (optional)
   */
  bmpPreview?: string
  /**
   * All of entities in this block record
   */
  entities: DwgEntity[]
}
