#!/bin/sh
# dwg -> json
# json -> dwg2
# teigha dwg2 -> dxf just to confirm written DWG readability
d=${1:-example_2000}
b=$(basename $d .dwg)
dir=$(dirname $d)
r=$(basename $dir)
case $dir in
    *test/test-data) ;;
    *test/test-data/*) r=`basename $(dirname $d)`; b=${b}_${r} ;;
    *td) ;;
    *td/*)             r=`basename $(dirname $d)`; b=${b}_${r} ;;
esac
case $r in
    20*)      ;;
    r9)       r=9 ;;
    r1[0234]) r=${r:1} ;;
    *)  case $b in
            *_20*)      r=${b:(-4)}; f=`basename $b _$r` ;;
            *_r9)       r=9;         f=`basename $b _r$r` ;;
            *_r1[0234]) r=${b:(-2)}; f=`basename $b _r$r` ;;
        esac ;;
esac

# first create a dwg log to compare against
./log -v3 $d
mv $b.log $b.log.orig
rm $b.json $b.dwg 2>/dev/null

./json -v4 $d
if [ -f $b.json ]; then
    ./dwg -y -v4 $b.json
fi

if [ -f $b.dwg ]; then
    case `uname` in
        Darwin)  TeighaFileConverter=/Applications/TeighaFileConverter.app/Contents/MacOS/TeighaFileConverter ;;
        Linux)   TeighaFileConverter=/usr/bin/TeighaFileConverter ;;
        Windows) TeighaFileConverter=TeighaFileConverter ;;
    esac
    if [ -x $TeighaFileConverter ]; then
        cp $b.dwg test/
        echo TeighaFileConverter "test" "." ACAD$r DXF 0 1 $b.dwg
        $TeighaFileConverter "test" "." ACAD$r DXF 0 1 $b.dwg
        mv $b.dxf.err $b.json.err
        cat $b.json.err
    else
        echo TeighaFileConverter not installed
    fi

    ./log -v3 $b.dwg
    # bash only
    #diff -bu <(grep -B1 'Add entity ' $b.log.orig) <(grep -B1 'Add entity ' $b.log)
    echo diff -bu $b.log.orig $b.log
    diff -bu $b.log.orig $b.log
fi
