#!/bin/sh
set -e
VER=0.4.8
wget -q -O pslib-$VER.tar.gz https://sourceforge.net/projects/pslib/files/pslib/$VER/pslib-$VER.tar.gz/download
tar xfz pslib-$VER.tar.gz
cd pslib-$VER
# sh autogen.sh
./configure --disable-nls --prefix=/usr
make
#make check
sudo make install
