#!/bin/sh
d=${1:-example_2000}
b=$(basename $d .dwg)
r=2000
if [ $(dirname $d) != . ]; then
    r=$(dirname $d)
fi
case $r in
    20*)      ;;
    r9)       r=9 ;;
    r1[0234]) r=${r:1} ;;
    *)  case $f in
            *_20*)      r=${b:(-4)}; f=`basename $b _$r` ;;
            *_r9)       r=9;         f=`basename $b _r$r` ;;
            *_r1[0234]) r=${b:(-2)}; f=`basename $b _r$r` ;;
            *) echo wrong version $r ;;
        esac ;;
esac
if [ $(dirname $d) != . ]; then
    b=${b}_${r}
fi
case `uname` in
    Darwin)  TeighaFileConverter=/Applications/TeighaFileConverter.app/Contents/MacOS/TeighaFileConverter ;;
    Linux)   TeighaFileConverter=/usr/bin/TeighaFileConverter ;;
    Windows) TeighaFileConverter=TeighaFileConverter ;;
esac

./log -v4 $d
rm $d.dwg 2>/dev/null
./dxf -y -v4 $d

make -s -j4 -C programs dwg2dxf
echo programs/dwg2dxf -v4 -y $b.dwg 2\>$b.dwg.log
programs/dwg2dxf -v4 -y $b.dwg 2>$b.dwg.log

cp $b.dwg test/
echo TeighaFileConverter "test" "." ACAD2000 DXF 0 1 $b.dwg
$TeighaFileConverter "test" "." ACAD2000 DXF 0 1 $b.dwg
cat $b.dxf.err

echo diff -bu $b.log $b.dwg.log
diff -bu $b.log $b.dwg.log

