all :
check : 3dsolid arc attdef attrib block body circle dim_aligned dim_ang2ln dim_ang3pt dim_diameter dim_linear dim_ordinate dim_radius ellipse endblk insert line lwpline minsert mline mtext point polyline_2d polyline_3d polyline_mesh polyline_pface ray region seqend shape solid text tolerance trace vertex_2d vertex_3d vertex_mesh vertex_pface xline 
3dsolid : 3dsolid.c
	gcc -g -o 3dsolid 3dsolid.c -lredwg -lm
arc : arc.c
	gcc -g -o arc arc.c -lredwg -lm
attdef : attdef.c
	gcc -g -o attdef attdef.c -lredwg -lm
attrib : attrib.c
	gcc -g -o attrib attrib.c -lredwg -lm
block : block.c
	gcc -g -o block block.c -lredwg -lm
body : body.c
	gcc -g -o body body.c -lredwg -lm
circle : circle.c
	gcc -g -o circle circle.c -lredwg -lm
dim_aligned : dim_aligned.c
	gcc -g -o dim_aligned dim_aligned.c -lredwg -lm
dim_ang2ln : dim_ang2ln.c
	gcc -g -o dim_ang2ln dim_ang2ln.c -lredwg -lm
dim_ang3pt : dim_ang3pt.c
	gcc -g -o dim_ang3pt dim_ang3pt.c -lredwg -lm
dim_diameter : dim_diameter.c
	gcc -g -o dim_diameter dim_diameter.c -lredwg -lm
dim_linear : dim_linear.c
	gcc -g -o dim_linear dim_linear.c -lredwg -lm
dim_ordinate : dim_ordinate.c
	gcc -g -o dim_ordinate dim_ordinate.c -lredwg -lm
dim_radius : dim_radius.c
	gcc -g -o dim_radius dim_radius.c -lredwg -lm
ellipse : ellipse.c
	gcc -g -o ellipse ellipse.c -lredwg -lm
endblk : endblk.c
	gcc -g -o endblk endblk.c -lredwg -lm
insert : insert.c
	gcc -g -o insert insert.c -lredwg -lm
line : line.c
	gcc -g -o line line.c -lredwg -lm
lwpline : lwpline.c
	gcc -g -o lwpline lwpline.c -lredwg -lm
minsert : minsert.c
	gcc -g -o minsert minsert.c -lredwg -lm
mline : mline.c
	gcc -g -o mline mline.c -lredwg -lm
mtext : mtext.c
	gcc -g -o mtext mtext.c -lredwg -lm
#ole2frame : ole2frame.c
#	gcc -g -o ole2frame ole2frame.c -lredwg -lm
point : point.c
	gcc -g -o point point.c -lredwg -lm
polyline_2d : polyline_2d.c
	gcc -g -o polyline_2d polyline_2d.c -lredwg -lm
polyline_3d : polyline_3d.c
	gcc -g -o polyline_3d polyline_3d.c -lredwg -lm
polyline_mesh : polyline_mesh.c
	gcc -g -o polyline_mesh polyline_mesh.c -lredwg -lm
polyline_pface : polyline_pface.c
	gcc -g -o polyline_pface polyline_pface.c -lredwg -lm
ray : ray.c
	gcc -g -o ray ray.c -lredwg -lm
region : region.c
	gcc -g -o region region.c -lredwg -lm
seqend : seqend.c
	gcc -g -o seqend seqend.c -lredwg -lm
shape : shape.c
	gcc -g -o shape shape.c -lredwg -lm
solid : solid.c
	gcc -g -o solid solid.c -lredwg -lm
text : text.c
	gcc -g -o text text.c -lredwg -lm
tolerance : tolerance.c
	gcc -g -o tolerance tolerance.c -lredwg -lm
trace : trace.c
	gcc -g -o trace trace.c -lredwg -lm
vertex_2d : vertex_2d.c
	gcc -g -o vertex_2d vertex_2d.c -lredwg -lm
vertex_3d : vertex_3d.c
	gcc -g -o vertex_3d vertex_3d.c -lredwg -lm
vertex_mesh : vertex_mesh.c
	gcc -g -o vertex_mesh vertex_mesh.c -lredwg -lm
vertex_pface : vertex_pface.c
	gcc -g -o vertex_pface vertex_pface.c -lredwg -lm
xline : xline.c
	gcc -g -o xline xline.c -lredwg -lm\

clean : 
