// TODO unstable
#define DWG_TYPE DWG_TYPE_ASSOCREVOLVEDSURFACEACTIONBODY
#include "common.c"

void
api_process (dwg_object *obj)
{
  int error, isnew;
  ASSOCPATHBASEDSURFACEACTIONBODY_fields;
  BITCODE_H *deps;
  BITCODE_BL class_version;

  Dwg_Version_Type dwg_version = obj->parent->header.version;
  dwg_obj_assocrevolvedsurfaceactionbody *_obj = dwg_object_to_ASSOCREVOLVEDSURFACEACTIONBODY (obj);

  // ASSOCACTIONPARAM:
  CHK_ENTITY_TYPE (_obj, ASSOCREVOLVEDSURFACEACTIONBODY, is_r2013, BS);
  SINCE (R_2013) {
    CHK_ENTITY_TYPE (_obj, ASSOCREVOLVEDSURFACEACTIONBODY, aap_version, BL);
    CHK_ENTITY_MAX  (_obj, ASSOCREVOLVEDSURFACEACTIONBODY, aap_version, BL, 2);
  }
  CHK_ENTITY_UTF8TEXT (_obj, ASSOCREVOLVEDSURFACEACTIONBODY, name);
  CHK_ASSOCPARAMBASEDACTIONBODY (ASSOCREVOLVEDSURFACEACTIONBODY);
  // AcDbAssocSurfaceActionBody
  CHK_ENTITY_TYPE (_obj, ASSOCREVOLVEDSURFACEACTIONBODY, sab_status, BL);
  CHK_ENTITY_TYPE (_obj, ASSOCREVOLVEDSURFACEACTIONBODY, sab_b1, B);
  CHK_ENTITY_TYPE (_obj, ASSOCREVOLVEDSURFACEACTIONBODY, sab_l2, BL);
  CHK_ENTITY_TYPE (_obj, ASSOCREVOLVEDSURFACEACTIONBODY, sab_b2, B);
  CHK_ENTITY_TYPE (_obj, ASSOCREVOLVEDSURFACEACTIONBODY, sab_s1, BS);
  CHK_ENTITY_H (_obj, ASSOCREVOLVEDSURFACEACTIONBODY, sab_h330);
  // AcDbAssocPathBasedSurfaceActionBody
  CHK_ENTITY_TYPE (_obj, ASSOCREVOLVEDSURFACEACTIONBODY, pbsab_status, BL);

  CHK_ENTITY_TYPE (_obj, ASSOCREVOLVEDSURFACEACTIONBODY, class_version, BL); 
}
