// TODO unstable
#define DWG_TYPE DWG_TYPE_ASSOCPATCHSURFACEACTIONBODY
#include "common.c"

void
api_process (dwg_object *obj)
{
  int error, isnew;
  ASSOCPATHBASEDSURFACEACTIONBODY_fields;
  BITCODE_H *deps;

  Dwg_Version_Type dwg_version = obj->parent->header.version;
  dwg_obj_assocpatchsurfaceactionbody *_obj = dwg_object_to_ASSOCPATCHSURFACEACTIONBODY (obj);

  // ASSOCACTIONPARAM:
  CHK_ENTITY_TYPE (_obj, ASSOCPATCHSURFACEACTIONBODY, is_r2013, BS);
  SINCE (R_2013) {
    CHK_ENTITY_TYPE (_obj, ASSOCPATCHSURFACEACTIONBODY, aap_version, BL);
    CHK_ENTITY_MAX  (_obj, ASSOCPATCHSURFACEACTIONBODY, aap_version, BL, 2);
  }
  CHK_ENTITY_UTF8TEXT (_obj, ASSOCPATCHSURFACEACTIONBODY, name);
  CHK_ASSOCPARAMBASEDACTIONBODY (ASSOCPATCHSURFACEACTIONBODY);
  // AcDbAssocSurfaceActionBody
  CHK_ENTITY_TYPE (_obj, ASSOCPATCHSURFACEACTIONBODY, sab_status, BL);
  CHK_ENTITY_TYPE (_obj, ASSOCPATCHSURFACEACTIONBODY, sab_b1, B);
  CHK_ENTITY_TYPE (_obj, ASSOCPATCHSURFACEACTIONBODY, sab_l2, BL);
  CHK_ENTITY_TYPE (_obj, ASSOCPATCHSURFACEACTIONBODY, sab_b2, B);
  CHK_ENTITY_TYPE (_obj, ASSOCPATCHSURFACEACTIONBODY, sab_s1, BS);
  CHK_ENTITY_H (_obj, ASSOCPATCHSURFACEACTIONBODY, sab_h330);
  // AcDbAssocPathBasedSurfaceActionBody
  CHK_ENTITY_TYPE (_obj, ASSOCPATCHSURFACEACTIONBODY, pbsab_status, BL);
}
