// TODO unstable
#define DWG_TYPE DWG_TYPE_ASSOCPLANESURFACEACTIONBODY
#include "common.c"

void
api_process (dwg_object *obj)
{
  int error;
  ASSOCPATHBASEDSURFACEACTIONBODY_fields
  BITCODE_BL class_version;

  Dwg_Version_Type dwg_version = obj->parent->header.version;
  dwg_obj_assocplanesurfaceactionbody *_obj = dwg_object_to_ASSOCPLANESURFACEACTIONBODY (obj);

  CHK_ENTITY_TYPE (_obj, ASSOCPLANESURFACEACTIONBODY, aab_version, BL);
  CHK_ENTITY_TYPE (_obj, ASSOCPLANESURFACEACTIONBODY, pab_status, BL);
  CHK_ENTITY_TYPE (_obj, ASSOCPLANESURFACEACTIONBODY, pab_l2, BL);
  CHK_ENTITY_TYPE (_obj, ASSOCPLANESURFACEACTIONBODY, num_deps, BL);
  CHK_ENTITY_HV   (_obj, ASSOCPLANESURFACEACTIONBODY, readdeps, num_deps);
  CHK_ENTITY_TYPE (_obj, ASSOCPLANESURFACEACTIONBODY, pab_l4, BL);
  CHK_ENTITY_TYPE (_obj, ASSOCPLANESURFACEACTIONBODY, pab_l5, BL);
  CHK_ENTITY_HV   (_obj, ASSOCPLANESURFACEACTIONBODY, writedeps, num_deps);
  CHK_ENTITY_TYPE (_obj, ASSOCPLANESURFACEACTIONBODY, sab_status, BL);
  CHK_ENTITY_TYPE (_obj, ASSOCPLANESURFACEACTIONBODY, sab_b1, B);
  CHK_ENTITY_TYPE (_obj, ASSOCPLANESURFACEACTIONBODY, sab_l2, BL);
  CHK_ENTITY_TYPE (_obj, ASSOCPLANESURFACEACTIONBODY, sab_b2, B);
  CHK_ENTITY_TYPE (_obj, ASSOCPLANESURFACEACTIONBODY, sab_s1, BS);
  CHK_ENTITY_TYPE (_obj, ASSOCPLANESURFACEACTIONBODY, pbsab_status, BL);

  CHK_ENTITY_TYPE (_obj, ASSOCPLANESURFACEACTIONBODY, class_version, BL); 
}
