// TODO unstable
#define DWG_TYPE DWG_TYPE_ASSOCFILLETSURFACEACTIONBODY
#include "common.c"

void
api_process (dwg_object *obj)
{
  int error, isnew;
  ASSOCPATHBASEDSURFACEACTIONBODY_fields;
  BITCODE_H *deps;
  // AcDbAssocFilletSurfaceActionBody
  BITCODE_BL class_version;
  BITCODE_BS status;
  BITCODE_2RD pt1, pt2;

  Dwg_Version_Type dwg_version = obj->parent->header.version;
  dwg_obj_assocfilletsurfaceactionbody *_obj = dwg_object_to_ASSOCFILLETSURFACEACTIONBODY (obj);

  // ASSOCACTIONPARAM:
  CHK_ENTITY_TYPE (_obj, ASSOCFILLETSURFACEACTIONBODY, is_r2013, BS);
  SINCE (R_2013) {
    CHK_ENTITY_TYPE (_obj, ASSOCFILLETSURFACEACTIONBODY, aap_version, BL);
    CHK_ENTITY_MAX  (_obj, ASSOCFILLETSURFACEACTIONBODY, aap_version, BL, 2);
  }
  CHK_ENTITY_UTF8TEXT (_obj, ASSOCFILLETSURFACEACTIONBODY, name);
  CHK_ASSOCPARAMBASEDACTIONBODY (ASSOCFILLETSURFACEACTIONBODY);
  // AcDbAssocSurfaceActionBody
  CHK_ENTITY_TYPE (_obj, ASSOCFILLETSURFACEACTIONBODY, sab_status, BL);
  CHK_ENTITY_TYPE (_obj, ASSOCFILLETSURFACEACTIONBODY, sab_b1, B);
  CHK_ENTITY_TYPE (_obj, ASSOCFILLETSURFACEACTIONBODY, sab_l2, BL);
  CHK_ENTITY_TYPE (_obj, ASSOCFILLETSURFACEACTIONBODY, sab_b2, B);
  CHK_ENTITY_TYPE (_obj, ASSOCFILLETSURFACEACTIONBODY, sab_s1, BS);
  CHK_ENTITY_H (_obj, ASSOCFILLETSURFACEACTIONBODY, sab_h330);
  // AcDbAssocPathBasedSurfaceActionBody
  CHK_ENTITY_TYPE (_obj, ASSOCFILLETSURFACEACTIONBODY, pbsab_status, BL);

  CHK_ENTITY_TYPE (_obj, ASSOCFILLETSURFACEACTIONBODY, class_version, BL);
  CHK_ENTITY_TYPE (_obj, ASSOCFILLETSURFACEACTIONBODY, status, BS);
  CHK_ENTITY_2RD  (_obj, ASSOCFILLETSURFACEACTIONBODY, pt1);
  CHK_ENTITY_2RD  (_obj, ASSOCFILLETSURFACEACTIONBODY, pt2);
}
