// TODO unstable
#define DWG_TYPE DWG_TYPE_ASSOCBLENDSURFACEACTIONBODY
#include "common.c"

void
api_process (dwg_object *obj)
{
  int error, isnew;
  ASSOCPATHBASEDSURFACEACTIONBODY_fields;
  BITCODE_H *deps;
  // AcDbAssocExtrudedSurfaceActionBody
  BITCODE_BL class_version;
  BITCODE_B b1;
  BITCODE_B b2;
  BITCODE_B b3;
  BITCODE_B b4;
  BITCODE_B b5;
  BITCODE_BS bs1;
  BITCODE_BS bs2;

  Dwg_Version_Type dwg_version = obj->parent->header.version;
  dwg_obj_assocblendsurfaceactionbody *_obj = dwg_object_to_ASSOCBLENDSURFACEACTIONBODY (obj);

  // ASSOCACTIONPARAM:
  CHK_ENTITY_TYPE (_obj, ASSOCBLENDSURFACEACTIONBODY, is_r2013, BS);
  SINCE (R_2013) {
    CHK_ENTITY_TYPE (_obj, ASSOCBLENDSURFACEACTIONBODY, aap_version, BL);
    CHK_ENTITY_MAX  (_obj, ASSOCBLENDSURFACEACTIONBODY, aap_version, BL, 2);
  }
  CHK_ENTITY_UTF8TEXT (_obj, ASSOCBLENDSURFACEACTIONBODY, name);
  CHK_ASSOCPARAMBASEDACTIONBODY (ASSOCBLENDSURFACEACTIONBODY);
  // AcDbAssocSurfaceActionBody
  CHK_ENTITY_TYPE (_obj, ASSOCBLENDSURFACEACTIONBODY, sab_status, BL);
  CHK_ENTITY_TYPE (_obj, ASSOCBLENDSURFACEACTIONBODY, sab_b1, B);
  CHK_ENTITY_TYPE (_obj, ASSOCBLENDSURFACEACTIONBODY, sab_l2, BL);
  CHK_ENTITY_TYPE (_obj, ASSOCBLENDSURFACEACTIONBODY, sab_b2, B);
  CHK_ENTITY_TYPE (_obj, ASSOCBLENDSURFACEACTIONBODY, sab_s1, BS);
  CHK_ENTITY_H (_obj, ASSOCBLENDSURFACEACTIONBODY, sab_h330);
  // AcDbAssocPathBasedSurfaceActionBody
  CHK_ENTITY_TYPE (_obj, ASSOCBLENDSURFACEACTIONBODY, pbsab_status, BL);

  CHK_ENTITY_TYPE (_obj, ASSOCBLENDSURFACEACTIONBODY, class_version, BL);
  CHK_ENTITY_TYPE (_obj, ASSOCBLENDSURFACEACTIONBODY, b1, B);
  CHK_ENTITY_TYPE (_obj, ASSOCBLENDSURFACEACTIONBODY, b2, B);
  CHK_ENTITY_TYPE (_obj, ASSOCBLENDSURFACEACTIONBODY, b3, B);
  CHK_ENTITY_TYPE (_obj, ASSOCBLENDSURFACEACTIONBODY, bs1, BS);
  CHK_ENTITY_TYPE (_obj, ASSOCBLENDSURFACEACTIONBODY, b4, B);
  CHK_ENTITY_TYPE (_obj, ASSOCBLENDSURFACEACTIONBODY, b5, B);
  CHK_ENTITY_TYPE (_obj, ASSOCBLENDSURFACEACTIONBODY, bs2, BS);
}
