#define DWG_TYPE DWG_TYPE_DIMSTYLE
#include "common.c"

void
api_process (dwg_object *obj)
{
  int error, isnew;
  BITCODE_RS flag;
  BITCODE_B flag0;
  BITCODE_T name;
  BITCODE_RS used;
  BITCODE_B xrefref;
  BITCODE_BS xrefindex_plus1;
  BITCODE_B xrefdep;

  BITCODE_B DIMTOL;
  BITCODE_B DIMLIM;
  BITCODE_B DIMTIH;
  BITCODE_B DIMTOH;
  BITCODE_B DIMSE1;
  BITCODE_B DIMSE2;
  BITCODE_B DIMALT;
  BITCODE_B DIMTOFL;
  BITCODE_B DIMSAH;
  BITCODE_B DIMTIX;
  BITCODE_B DIMSOXD;
  BITCODE_BS DIMALTD;   /*!< r13-r14 only RC */
  BITCODE_BS DIMZIN;    /*!< r13-r14 only RC */
  BITCODE_B DIMSD1;
  BITCODE_B DIMSD2;
  BITCODE_BS DIMTOLJ;   /*!< r13-r14 only RC */
  BITCODE_BS DIMJUST;   /*!< r13-r14 only RC */
  BITCODE_BS DIMFIT;    /*!< r13-r14 only RC */
  BITCODE_B DIMUPT;
  BITCODE_BS DIMTZIN;   /*!< r13-r14 only RC */
  BITCODE_BS DIMMALTZ;  /*!< r13-r14 only RC */
  BITCODE_BS DIMMALTTZ; /*!< r13-r14 only RC */
  BITCODE_BS DIMTAD;    /*!< r13-r14 only RC */
  BITCODE_BS DIMUNIT;
  BITCODE_BS DIMAUNIT;
  BITCODE_BS DIMDEC;
  BITCODE_BS DIMTDEC;
  BITCODE_BS DIMALTU;
  BITCODE_BS DIMALTTD;
  /* BITCODE_H DIMTXSTY; */
  BITCODE_BD DIMSCALE;
  BITCODE_BD DIMASZ;
  BITCODE_BD DIMEXO;
  BITCODE_BD DIMDLI;
  BITCODE_BD DIMEXE;
  BITCODE_BD DIMRND;
  BITCODE_BD DIMDLE;
  BITCODE_BD DIMTP;
  BITCODE_BD DIMTM;
  BITCODE_BD DIMFXL;
  BITCODE_BD DIMJOGANG;
  BITCODE_BS DIMTFILL;
  BITCODE_CMC DIMTFILLCLR;
  BITCODE_BS DIMAZIN;
  BITCODE_BS DIMARCSYM;
  BITCODE_BD DIMTXT;
  BITCODE_BD DIMCEN;
  BITCODE_BD DIMTSZ;
  BITCODE_BD DIMALTF;
  BITCODE_BD DIMLFAC;
  BITCODE_BD DIMTVP;
  BITCODE_BD DIMTFAC;
  BITCODE_BD DIMGAP;
  BITCODE_T DIMPOST;
  BITCODE_T DIMAPOST;
  BITCODE_T DIMBLK_T;
  BITCODE_T DIMBLK1_T;
  BITCODE_T DIMBLK2_T;
  BITCODE_BD DIMALTRND;
  BITCODE_RS DIMCLRD_N; /* preR13 */
  BITCODE_RS DIMCLRE_N; /* preR13 */
  BITCODE_RS DIMCLRT_N; /* preR13 */
  BITCODE_CMC DIMCLRD;
  BITCODE_CMC DIMCLRE;
  BITCODE_CMC DIMCLRT;
  BITCODE_BS DIMADEC;
  BITCODE_BS DIMFRAC;
  BITCODE_BS DIMLUNIT;
  BITCODE_BS DIMDSEP;
  BITCODE_BS DIMTMOVE;
  BITCODE_BS DIMALTZ;
  BITCODE_BS DIMALTTZ;
  BITCODE_BS DIMATFIT;
  BITCODE_B DIMFXLON;   /*!< r2007+ */
  BITCODE_B  DIMTXTDIRECTION; /*!< r2010+ */
  BITCODE_BD DIMALTMZF; /*!< r2010+ */
  BITCODE_T  DIMALTMZS; /*!< r2010+ */
  BITCODE_BD DIMMZF;    /*!< r2010+ */
  BITCODE_T  DIMMZS;    /*!< r2010+ */
  BITCODE_BSd DIMLWD;
  BITCODE_BSd DIMLWE;
  BITCODE_H extref;
  BITCODE_H DIMTXSTY;
  BITCODE_H DIMLDRBLK;
  BITCODE_H DIMBLK;
  BITCODE_H DIMBLK1;
  BITCODE_H DIMBLK2;
  BITCODE_H DIMLTYPE;
  BITCODE_H DIMLTEX1;
  BITCODE_H DIMLTEX2;
  
  Dwg_Version_Type dwg_version = obj->parent->header.version;
  dwg_obj_dimstyle *_obj = dwg_object_to_DIMSTYLE (obj);

  CHK_ENTITY_TYPE (_obj, DIMSTYLE, flag, RC, flag);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, flag0, B, flag0);
  CHK_ENTITY_UTF8TEXT (_obj, DIMSTYLE, name, name);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, used, RS, used);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, xrefref, B, xrefref);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, xrefindex_plus1, BS, xrefindex_plus1);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, xrefdep, B, xrefdep);

  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTOL, B, DIMTOL);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMLIM, B, DIMLIM);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTIH, B, DIMTIH);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTOH, B, DIMTOH);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMSE1, B, DIMSE1);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMSE2, B, DIMSE2);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMALT, B, DIMALT);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTOFL, B, DIMTOFL);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMSAH, B, DIMSAH);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTIX, B, DIMTIX);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMSOXD, B, DIMSOXD);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMALTD, BS, DIMALTD);   /*!< r13-r14 only RC */
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMZIN, BS, DIMZIN);    /*!< r13-r14 only RC */
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMSD1, B, DIMSD1);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMSD2, B, DIMSD2);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTOLJ, BS, DIMTOLJ);   /*!< r13-r14 only RC */
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMJUST, BS, DIMJUST);   /*!< r13-r14 only RC */
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMFIT, BS, DIMFIT);    /*!< r13-r14 only RC */
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMUPT, B, DIMUPT);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTZIN, BS, DIMTZIN);   /*!< r13-r14 only RC */
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMMALTZ, BS, DIMMALTZ);  /*!< r13-r14 only RC */
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMMALTTZ, BS, DIMMALTTZ); /*!< r13-r14 only RC */
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTAD, BS, DIMTAD);    /*!< r13-r14 only RC */
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMUNIT, BS, DIMUNIT);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMAUNIT, BS, DIMAUNIT);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMDEC, BS, DIMDEC);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTDEC, BS, DIMTDEC);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMALTU, BS, DIMALTU);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMALTTD, BS, DIMALTTD);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMSCALE, BD, DIMSCALE);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMASZ, BD, DIMASZ);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMEXO, BD, DIMEXO);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMDLI, BD, DIMDLI);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMEXE, BD, DIMEXE);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMRND, BD, DIMRND);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMDLE, BD, DIMDLE);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTP, BD, DIMTP);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTM, BD, DIMTM);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMFXL, BD, DIMFXL);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMJOGANG, BD, DIMJOGANG);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTFILL, BS, DIMTFILL);
  CHK_ENTITY_CMC (_obj, DIMSTYLE, DIMTFILLCLR, DIMTFILLCLR);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMAZIN, BS, DIMAZIN);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMARCSYM, BS, DIMARCSYM);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTXT, BD, DIMTXT);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMCEN, BD, DIMCEN);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTSZ, BD, DIMTSZ);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMALTF, BD, DIMALTF);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMLFAC, BD, DIMLFAC);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTVP, BD, DIMTVP);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTFAC, BD, DIMTFAC);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMGAP, BD, DIMGAP);
  CHK_ENTITY_UTF8TEXT (_obj, DIMSTYLE, DIMPOST, DIMPOST);
  CHK_ENTITY_UTF8TEXT (_obj, DIMSTYLE, DIMAPOST, DIMAPOST);
  CHK_ENTITY_UTF8TEXT (_obj, DIMSTYLE, DIMBLK_T, DIMBLK_T);
  CHK_ENTITY_UTF8TEXT (_obj, DIMSTYLE, DIMBLK1_T, DIMBLK1_T);
  CHK_ENTITY_UTF8TEXT (_obj, DIMSTYLE, DIMBLK2_T, DIMBLK2_T);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMALTRND, BD, DIMALTRND);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMCLRD_N, RS, DIMCLRD_N); /* preR13 */
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMCLRE_N, RS, DIMCLRE_N); /* preR13 */
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMCLRT_N, RS, DIMCLRT_N); /* preR13 */
  CHK_ENTITY_CMC (_obj, DIMSTYLE, DIMCLRD, DIMCLRD);
  CHK_ENTITY_CMC (_obj, DIMSTYLE, DIMCLRE, DIMCLRE);
  CHK_ENTITY_CMC (_obj, DIMSTYLE, DIMCLRT, DIMCLRT);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMADEC, BS, DIMADEC);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMFRAC, BS, DIMFRAC);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMLUNIT, BS, DIMLUNIT);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMDSEP, BS, DIMDSEP);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTMOVE, BS, DIMTMOVE);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMALTZ, BS, DIMALTZ);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMALTTZ, BS, DIMALTTZ);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMATFIT, BS, DIMATFIT);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMFXLON, B, DIMFXLON);   /*!< r2007+ */
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMTXTDIRECTION, B, DIMTXTDIRECTION); /*!< r2010+ */
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMALTMZF, BD, DIMALTMZF); /*!< r2010+ */
  CHK_ENTITY_UTF8TEXT (_obj, DIMSTYLE, DIMALTMZS, DIMALTMZS); /*!< r2010+ */
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMMZF, BD, DIMMZF);    /*!< r2010+ */
  CHK_ENTITY_UTF8TEXT (_obj, DIMSTYLE, DIMMZS, DIMMZS);    /*!< r2010+ */
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMLWD, BSd, DIMLWD);
  CHK_ENTITY_TYPE (_obj, DIMSTYLE, DIMLWE, BSd, DIMLWE);
  CHK_ENTITY_H (_obj, DIMSTYLE, extref, extref);
  CHK_ENTITY_H (_obj, DIMSTYLE, DIMTXSTY, DIMTXSTY);
  CHK_ENTITY_H (_obj, DIMSTYLE, DIMLDRBLK, DIMLDRBLK);
  CHK_ENTITY_H (_obj, DIMSTYLE, DIMBLK, DIMBLK);
  CHK_ENTITY_H (_obj, DIMSTYLE, DIMBLK1, DIMBLK1);
  CHK_ENTITY_H (_obj, DIMSTYLE, DIMBLK2, DIMBLK2);
  CHK_ENTITY_H (_obj, DIMSTYLE, DIMLTYPE, DIMLTYPE);
  CHK_ENTITY_H (_obj, DIMSTYLE, DIMLTEX1, DIMLTEX1);
  CHK_ENTITY_H (_obj, DIMSTYLE, DIMLTEX2, DIMLTEX2);
}
