/* ANSI-C code produced by gperf version 3.1 */
/* Command-line: gperf --output-file src/objects.tmp.c src/objects.in  */
/* Computed positions: -k'1-2,6,8,10,$' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gperf@gnu.org>."
#endif

#line 1 "src/objects.in"
 // -*- mode: c -*-
/*****************************************************************************/
/*  LibreDWG - free implementation of the DWG file format                    */
/*                                                                           */
/*  Copyright (C) 2020 Free Software Foundation, Inc.                        */
/*                                                                           */
/*  This library is free software, licensed under the terms of the GNU       */
/*  General Public License as published by the Free Software Foundation,     */
/*  either version 3 of the License, or (at your option) any later version.  */
/*  You should have received a copy of the GNU General Public License        */
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.    */
/*****************************************************************************/

/*
 * objects.c: define all our entity and object names as hashmap,
 *            generated via gperf from object.in,
 *            which is generated by gen-dynapi.pl
 *
 * written Reini Urban
 */

#include <string.h>
#include "config.h"
#include "dwg.h"
#include "common.h"

static const struct _dwg_dxfname * in_word_set (register const char *str, register size_t len);

#line 36 "src/objects.in"
struct _dwg_dxfname {int name; const char *const dxfname; const Dwg_Object_Type type; const unsigned isent:1;};

#define TOTAL_KEYWORDS 295
#define MIN_WORD_LENGTH 3
#define MAX_WORD_LENGTH 34
#define MIN_HASH_VALUE 9
#define MAX_HASH_VALUE 1331
/* maximum key range = 1323, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash (register const char *str, register size_t len)
{
  static const unsigned short asso_values[] =
    {
      1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332,
      1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332,
      1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332,
      1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332,
      1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332,
        15,    5,    0, 1332, 1332, 1332, 1332, 1332, 1332, 1332,
      1332, 1332, 1332, 1332, 1332,   10,   30,   65,  145,    5,
       180,  115,  180,   80,  340,  380,   35,   85,  340,   80,
         0,   85,   20,    5,    0,  355,  215,  255,  380,    0,
        40, 1332, 1332, 1332, 1332,  415,    0, 1332, 1332, 1332,
      1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332,
      1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332,
      1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332, 1332
    };
  register unsigned int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[9]];
#if defined __cplusplus && (__cplusplus >= 201703L || (__cplusplus >= 201103L && defined __clang_major__ && defined __clang_minor__ && __clang_major__ + (__clang_minor__ >= 9) > 3))
      [[fallthrough]];
#elif defined __GNUC__ && __GNUC__ >= 7
      __attribute__ ((__fallthrough__));
#endif
      /*FALLTHROUGH*/
      case 9:
      case 8:
        hval += asso_values[(unsigned char)str[7]+1];
#if defined __cplusplus && (__cplusplus >= 201703L || (__cplusplus >= 201103L && defined __clang_major__ && defined __clang_minor__ && __clang_major__ + (__clang_minor__ >= 9) > 3))
      [[fallthrough]];
#elif defined __GNUC__ && __GNUC__ >= 7
      __attribute__ ((__fallthrough__));
#endif
      /*FALLTHROUGH*/
      case 7:
      case 6:
        hval += asso_values[(unsigned char)str[5]];
#if defined __cplusplus && (__cplusplus >= 201703L || (__cplusplus >= 201103L && defined __clang_major__ && defined __clang_minor__ && __clang_major__ + (__clang_minor__ >= 9) > 3))
      [[fallthrough]];
#elif defined __GNUC__ && __GNUC__ >= 7
      __attribute__ ((__fallthrough__));
#endif
      /*FALLTHROUGH*/
      case 5:
      case 4:
      case 3:
      case 2:
        hval += asso_values[(unsigned char)str[1]];
#if defined __cplusplus && (__cplusplus >= 201703L || (__cplusplus >= 201103L && defined __clang_major__ && defined __clang_minor__ && __clang_major__ + (__clang_minor__ >= 9) > 3))
      [[fallthrough]];
#elif defined __GNUC__ && __GNUC__ >= 7
      __attribute__ ((__fallthrough__));
#endif
      /*FALLTHROUGH*/
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

struct stringpool_t
  {
    char stringpool_str9[sizeof("TEXT")];
    char stringpool_str15[sizeof("STYLE")];
    char stringpool_str20[sizeof("TABLE")];
    char stringpool_str21[sizeof("SPLINE")];
    char stringpool_str25[sizeof("RTEXT")];
    char stringpool_str30[sizeof("TRACE")];
    char stringpool_str33[sizeof("RAY")];
    char stringpool_str45[sizeof("LTYPE")];
    char stringpool_str50[sizeof("ASSOCARRAYACTIONBODY")];
    char stringpool_str51[sizeof("LAYOUT")];
    char stringpool_str56[sizeof("ASSOCARRAYMODIFYACTIONBODY")];
    char stringpool_str57[sizeof("ELLIPSE")];
    char stringpool_str59[sizeof("ASSOCARRAYPATHPARAMETERS")];
    char stringpool_str60[sizeof("ASSOCARRAYPOLARPARAMETERS")];
    char stringpool_str61[sizeof("ASSOCARRAYMODIFYPARAMETERS")];
    char stringpool_str66[sizeof("ASSOCARRAYRECTANGULARPARAMETERS")];
    char stringpool_str67[sizeof("ASSOCPERSSUBENTMANAGER")];
    char stringpool_str70[sizeof("LAYER")];
    char stringpool_str72[sizeof("PLANESURFACE")];
    char stringpool_str75[sizeof("TABLESTYLE")];
    char stringpool_str76[sizeof("ATTRIB")];
    char stringpool_str77[sizeof("ASSOCPLANESURFACEACTIONBODY")];
    char stringpool_str80[sizeof("SCALE")];
    char stringpool_str85[sizeof("POINT")];
    char stringpool_str86[sizeof("LEADER")];
    char stringpool_str90[sizeof("MTEXT")];
    char stringpool_str94[sizeof("BLOCKPROPERTIESTABLEGRIP")];
    char stringpool_str95[sizeof("BLOCKPROPERTIESTABLE")];
    char stringpool_str98[sizeof("ARC")];
    char stringpool_str101[sizeof("CAMERA")];
    char stringpool_str106[sizeof("ACSH_TORUS_CLASS")];
    char stringpool_str114[sizeof("BODY")];
    char stringpool_str116[sizeof("SECTION_SETTINGS")];
    char stringpool_str120[sizeof("LIGHT")];
    char stringpool_str124[sizeof("LINE")];
    char stringpool_str129[sizeof("SPATIAL_FILTER")];
    char stringpool_str130[sizeof("MLINE")];
    char stringpool_str133[sizeof("ACSH_BOOLEAN_CLASS")];
    char stringpool_str135[sizeof("SECTION_MANAGER")];
    char stringpool_str137[sizeof("GEODATA")];
    char stringpool_str138[sizeof("BLOCKBASEPOINTPARAMETER")];
    char stringpool_str140[sizeof("GROUP")];
    char stringpool_str142[sizeof("MLEADERSTYLE")];
    char stringpool_str143[sizeof("TABLEGEOMETRY")];
    char stringpool_str148[sizeof("ASSOCRESTOREENTITYSTATEACTIONBODY")];
    char stringpool_str150[sizeof("BLOCKRADIALCONSTRAINTPARAMETER")];
    char stringpool_str156[sizeof("RENDERENTRY")];
    char stringpool_str159[sizeof("LIGHTLIST")];
    char stringpool_str160[sizeof("APPID")];
    char stringpool_str161[sizeof("CIRCLE")];
    char stringpool_str163[sizeof("LEADEROBJECTCONTEXTDATA")];
    char stringpool_str166[sizeof("3DFACE")];
    char stringpool_str172[sizeof("TABLECONTENT")];
    char stringpool_str175[sizeof("IMAGE")];
    char stringpool_str179[sizeof("BLOCKPARAMDEPENDENCYBODY")];
    char stringpool_str180[sizeof("RASTERVARIABLES")];
    char stringpool_str184[sizeof("BLOCKPOLARGRIP")];
    char stringpool_str185[sizeof("MLINESTYLE")];
    char stringpool_str188[sizeof("ACSH_PYRAMID_CLASS")];
    char stringpool_str189[sizeof("ACSH_BOX_CLASS")];
    char stringpool_str190[sizeof("POINTPARAMETERENTITY")];
    char stringpool_str192[sizeof("MINSERT")];
    char stringpool_str195[sizeof("SHAPE")];
    char stringpool_str196[sizeof("LINEARPARAMETERENTITY")];
    char stringpool_str198[sizeof("ASSOCLOFTEDSURFACEACTIONBODY")];
    char stringpool_str202[sizeof("ACSH_SPHERE_CLASS")];
    char stringpool_str203[sizeof("MENTALRAYRENDERSETTINGS")];
    char stringpool_str205[sizeof("BLOCKLINEARGRIP")];
    char stringpool_str207[sizeof("RENDERGLOBAL")];
    char stringpool_str209[sizeof("BLOCKPOLARPARAMETER")];
    char stringpool_str220[sizeof("VPORT")];
    char stringpool_str222[sizeof("RENDERENVIRONMENT")];
    char stringpool_str224[sizeof("BASEPOINTPARAMETERENTITY")];
    char stringpool_str227[sizeof("ASSOCSWEPTSURFACEACTIONBODY")];
    char stringpool_str230[sizeof("BLOCKLINEARPARAMETER")];
    char stringpool_str232[sizeof("PERSUBENTMGR")];
    char stringpool_str234[sizeof("ALIGNMENTPARAMETERENTITY")];
    char stringpool_str235[sizeof("SOLID")];
    char stringpool_str239[sizeof("ACMESCOPE")];
    char stringpool_str240[sizeof("BLOCKLINEARCONSTRAINTPARAMETER")];
    char stringpool_str243[sizeof("ASSOCOFFSETSURFACEACTIONBODY")];
    char stringpool_str244[sizeof("RENDERSETTINGS")];
    char stringpool_str245[sizeof("OBJECT_PTR")];
    char stringpool_str246[sizeof("TEXTOBJECTCONTEXTDATA")];
    char stringpool_str249[sizeof("TOLERANCE")];
    char stringpool_str252[sizeof("CELLSTYLEMAP")];
    char stringpool_str263[sizeof("ASSOCVARIABLE")];
    char stringpool_str264[sizeof("DATATABLE")];
    char stringpool_str274[sizeof("MESH")];
    char stringpool_str279[sizeof("FLIPPARAMETERENTITY")];
    char stringpool_str281[sizeof("ACSH_SWEEP_CLASS")];
    char stringpool_str282[sizeof("DBCOLOR")];
    char stringpool_str288[sizeof("ORDDIMOBJECTCONTEXTDATA")];
    char stringpool_str289[sizeof("ASSOCOSNAPPOINTREFACTIONPARAM")];
    char stringpool_str291[sizeof("ASSOCEDGECHAMFERACTIONBODY")];
    char stringpool_str293[sizeof("ROTATIONPARAMETERENTITY")];
    char stringpool_str294[sizeof("ASSOCGEOMDEPENDENCY")];
    char stringpool_str297[sizeof("SWEPTSURFACE")];
    char stringpool_str298[sizeof("BLOCKDIAMETRICCONSTRAINTPARAMETER")];
    char stringpool_str303[sizeof("MATERIAL")];
    char stringpool_str304[sizeof("FIELDLIST")];
    char stringpool_str306[sizeof("SEQEND")];
    char stringpool_str308[sizeof("POINTCLOUDCOLORMAP")];
    char stringpool_str313[sizeof("ASSOCFILLETSURFACEACTIONBODY")];
    char stringpool_str315[sizeof("ASSOCEDGEACTIONPARAM")];
    char stringpool_str318[sizeof("OLEFRAME")];
    char stringpool_str329[sizeof("BLOCKVISIBILITYGRIP")];
    char stringpool_str331[sizeof("POINTCLOUDDEF_REACTOR")];
    char stringpool_str336[sizeof("PLACEHOLDER")];
    char stringpool_str340[sizeof("ASSOCVALUEDEPENDENCY")];
    char stringpool_str341[sizeof("BLOCKANGULARCONSTRAINTPARAMETER")];
    char stringpool_str344[sizeof("BLOCKHORIZONTALCONSTRAINTPARAMETER")];
    char stringpool_str345[sizeof("DICTIONARY")];
    char stringpool_str346[sizeof("LAYERFILTER")];
    char stringpool_str347[sizeof("ASSOCVERTEXACTIONPARAM")];
    char stringpool_str348[sizeof("BLKREFOBJECTCONTEXTDATA")];
    char stringpool_str349[sizeof("ARCALIGNEDTEXT")];
    char stringpool_str350[sizeof("DICTIONARYWDFLT")];
    char stringpool_str354[sizeof("BLOCKVISIBILITYPARAMETER")];
    char stringpool_str355[sizeof("ASSOCREVOLVEDSURFACEACTIONBODY")];
    char stringpool_str358[sizeof("ACSH_HISTORY_CLASS")];
    char stringpool_str359[sizeof("POLYLINE_PFACE")];
    char stringpool_str361[sizeof("ACSH_WEDGE_CLASS")];
    char stringpool_str367[sizeof("ACSH_FILLET_CLASS")];
    char stringpool_str368[sizeof("DICTIONARYVAR")];
    char stringpool_str371[sizeof("SECTIONVIEWSTYLE")];
    char stringpool_str373[sizeof("ACSH_CHAMFER_CLASS")];
    char stringpool_str375[sizeof("HATCH")];
    char stringpool_str376[sizeof("ATTDEF")];
    char stringpool_str382[sizeof("3DSOLID")];
    char stringpool_str386[sizeof("ASSOCTRIMSURFACEACTIONBODY")];
    char stringpool_str391[sizeof("ASSOC3POINTANGULARDIMACTIONBODY")];
    char stringpool_str394[sizeof("CSACDOCUMENTOPTIONS")];
    char stringpool_str396[sizeof("DYNAMICBLOCKPROXYNODE")];
    char stringpool_str397[sizeof("ASSOCBLENDSURFACEACTIONBODY")];
    char stringpool_str405[sizeof("ASSOCEDGEFILLETACTIONBODY")];
    char stringpool_str408[sizeof("ACSH_REVOLVE_CLASS")];
    char stringpool_str410[sizeof("FIELD")];
    char stringpool_str415[sizeof("ASSOCROTATEDDIMACTIONBODY")];
    char stringpool_str416[sizeof("DYNAMICBLOCKPURGEPREVENTER")];
    char stringpool_str417[sizeof("BLOCKVERTICALCONSTRAINTPARAMETER")];
    char stringpool_str418[sizeof("DIMSTYLE")];
    char stringpool_str421[sizeof("RAPIDRTRENDERSETTINGS")];
    char stringpool_str425[sizeof("XLINE")];
    char stringpool_str426[sizeof("INSERT")];
    char stringpool_str427[sizeof("ANNOTSCALEOBJECTCONTEXTDATA")];
    char stringpool_str428[sizeof("UCS")];
    char stringpool_str433[sizeof("BLOCKSTRETCHACTION")];
    char stringpool_str436[sizeof("BLOCKARRAYACTION")];
    char stringpool_str438[sizeof("IDBUFFER")];
    char stringpool_str439[sizeof("RADIMLGOBJECTCONTEXTDATA")];
    char stringpool_str443[sizeof("SECTIONOBJECT")];
    char stringpool_str444[sizeof("BLOCKPOINTPARAMETER")];
    char stringpool_str445[sizeof("POINTCLOUD")];
    char stringpool_str447[sizeof("ASSOCMLEADERACTIONBODY")];
    char stringpool_str448[sizeof("DIMASSOC")];
    char stringpool_str450[sizeof("BLOCK")];
    char stringpool_str453[sizeof("SORTENTSTABLE")];
    char stringpool_str455[sizeof("ASSOCFACEACTIONPARAM")];
    char stringpool_str457[sizeof("BLOCKROTATIONGRIP")];
    char stringpool_str461[sizeof("BLOCKSCALEACTION")];
    char stringpool_str464[sizeof("ASSOCPOINTREFACTIONPARAM")];
    char stringpool_str466[sizeof("ASSOCORDINATEDIMACTIONBODY")];
    char stringpool_str468[sizeof("STYLE_CONTROL")];
    char stringpool_str470[sizeof("BLOCKLOOKUPGRIP")];
    char stringpool_str473[sizeof("APPID_CONTROL")];
    char stringpool_str481[sizeof("IMAGEDEF_REACTOR")];
    char stringpool_str482[sizeof("BLOCKROTATIONPARAMETER")];
    char stringpool_str483[sizeof("POINTCLOUDDEF")];
    char stringpool_str485[sizeof("ASSOCPATHACTIONPARAM")];
    char stringpool_str489[sizeof("OLE2FRAME")];
    char stringpool_str495[sizeof("BLOCKLOOKUPPARAMETER")];
    char stringpool_str498[sizeof("LTYPE_CONTROL")];
    char stringpool_str499[sizeof("MLEADEROBJECTCONTEXTDATA")];
    char stringpool_str501[sizeof("POLYLINE_3D")];
    char stringpool_str505[sizeof("DUMMY")];
    char stringpool_str506[sizeof("LONG_TRANSACTION")];
    char stringpool_str507[sizeof("VIEW_CONTROL")];
    char stringpool_str508[sizeof("LAYER_CONTROL")];
    char stringpool_str511[sizeof("POLYLINE_2D")];
    char stringpool_str517[sizeof("PROXY_OBJECT")];
    char stringpool_str518[sizeof("TVDEVICEPROPERTIES")];
    char stringpool_str521[sizeof("DIMSTYLE_CONTROL")];
    char stringpool_str522[sizeof("LAYOUTPRINTCONFIG")];
    char stringpool_str527[sizeof("ASSOCDIMDEPENDENCYBODY")];
    char stringpool_str528[sizeof("BLOCK_CONTROL")];
    char stringpool_str533[sizeof("BLOCKPOLARSTRETCHACTION")];
    char stringpool_str534[sizeof("BLOCKREPRESENTATION")];
    char stringpool_str537[sizeof("ASSOC2DCONSTRAINTGROUP")];
    char stringpool_str538[sizeof("ANGDIMOBJECTCONTEXTDATA")];
    char stringpool_str541[sizeof("MULTILEADER")];
    char stringpool_str547[sizeof("ACMESTATEMGR")];
    char stringpool_str553[sizeof("ASSOCASMBODYACTIONPARAM")];
    char stringpool_str554[sizeof("VIEW")];
    char stringpool_str561[sizeof("ASSOCACTIONPARAM")];
    char stringpool_str568[sizeof("CONTEXTDATAMANAGER")];
    char stringpool_str570[sizeof("HELIX")];
    char stringpool_str571[sizeof("MTEXTATTRIBUTEOBJECTCONTEXTDATA")];
    char stringpool_str572[sizeof("XRECORD")];
    char stringpool_str575[sizeof("BACKGROUND")];
    char stringpool_str577[sizeof("ASSOCPATCHSURFACEACTIONBODY")];
    char stringpool_str581[sizeof("BLOCKGRIPLOCATIONCOMPONENT")];
    char stringpool_str586[sizeof("BLOCKXYPARAMETER")];
    char stringpool_str587[sizeof("RADIMOBJECTCONTEXTDATA")];
    char stringpool_str589[sizeof("ACSH_CYLINDER_CLASS")];
    char stringpool_str591[sizeof("GEOMAPIMAGE")];
    char stringpool_str592[sizeof("XYPARAMETERENTITY")];
    char stringpool_str597[sizeof("GEOPOSITIONMARKER")];
    char stringpool_str600[sizeof("ASSOCDEPENDENCY")];
    char stringpool_str602[sizeof("ALDIMOBJECTCONTEXTDATA")];
    char stringpool_str607[sizeof("PROXY_ENTITY")];
    char stringpool_str609[sizeof("ASSOCCOMPOUNDACTIONPARAM")];
    char stringpool_str613[sizeof("IMAGEDEF")];
    char stringpool_str618[sizeof("POLYLINE_MESH")];
    char stringpool_str620[sizeof("REVOLVEDSURFACE")];
    char stringpool_str623[sizeof("BLOCKFLIPPARAMETER")];
    char stringpool_str624[sizeof("POINTPATH")];
    char stringpool_str628[sizeof("MPOLYGON")];
    char stringpool_str638[sizeof("BLOCKUSERPARAMETER")];
    char stringpool_str642[sizeof("MTEXTOBJECTCONTEXTDATA")];
    char stringpool_str647[sizeof("ASSOCOBJECTACTIONPARAM")];
    char stringpool_str648[sizeof("ARC_DIMENSION")];
    char stringpool_str650[sizeof("LWPOLYLINE")];
    char stringpool_str655[sizeof("ACSH_CONE_CLASS")];
    char stringpool_str658[sizeof("DATALINK")];
    char stringpool_str660[sizeof("ACSH_LOFT_CLASS")];
    char stringpool_str661[sizeof("DIMENSION_ANG3PT")];
    char stringpool_str665[sizeof("NAVISWORKSMODEL")];
    char stringpool_str666[sizeof("DIMENSION_RADIUS")];
    char stringpool_str668[sizeof("DIMENSION_ORDINATE")];
    char stringpool_str673[sizeof("LOFTEDSURFACE")];
    char stringpool_str678[sizeof("VPORT_CONTROL")];
    char stringpool_str681[sizeof("DIMENSION_LINEAR")];
    char stringpool_str682[sizeof("POINTCLOUDEX")];
    char stringpool_str683[sizeof("DIMENSION_DIAMETER")];
    char stringpool_str685[sizeof("POINTCLOUDDEFEX")];
    char stringpool_str694[sizeof("POINTCLOUDDEF_REACTOR_EX")];
    char stringpool_str697[sizeof("WIPEOUT")];
    char stringpool_str703[sizeof("SUN")];
    char stringpool_str711[sizeof("REGION")];
    char stringpool_str712[sizeof("VERTEX_PFACE")];
    char stringpool_str713[sizeof("BLOCKFLIPGRIP")];
    char stringpool_str716[sizeof("BLOCKXYGRIP")];
    char stringpool_str717[sizeof("VERTEX_PFACE_FACE")];
    char stringpool_str720[sizeof("ACSH_BREP_CLASS")];
    char stringpool_str721[sizeof("VBA_PROJECT")];
    char stringpool_str730[sizeof("ASSOCALIGNEDDIMACTIONBODY")];
    char stringpool_str735[sizeof("VISIBILITYGRIPENTITY")];
    char stringpool_str736[sizeof("VISUALSTYLE")];
    char stringpool_str738[sizeof("VIEWPORT")];
    char stringpool_str740[sizeof("VISIBILITYPARAMETERENTITY")];
    char stringpool_str743[sizeof("ASSOCEXTENDSURFACEACTIONBODY")];
    char stringpool_str748[sizeof("SPATIAL_INDEX")];
    char stringpool_str752[sizeof("PLOTSETTINGS")];
    char stringpool_str754[sizeof("VERTEX_3D")];
    char stringpool_str759[sizeof("VERTEX_2D")];
    char stringpool_str760[sizeof("ASSOCEXTRUDEDSURFACEACTIONBODY")];
    char stringpool_str763[sizeof("SUNSTUDY")];
    char stringpool_str770[sizeof("BLOCKMOVEACTION")];
    char stringpool_str773[sizeof("BLOCKALIGNMENTGRIP")];
    char stringpool_str778[sizeof("UNDERLAY")];
    char stringpool_str787[sizeof("DMDIMOBJECTCONTEXTDATA")];
    char stringpool_str797[sizeof("BLOCKROTATEACTION")];
    char stringpool_str798[sizeof("BLOCKALIGNMENTPARAMETER")];
    char stringpool_str800[sizeof("DETAILVIEWSTYLE")];
    char stringpool_str805[sizeof("INDEX")];
    char stringpool_str806[sizeof("BLOCKALIGNEDCONSTRAINTPARAMETER")];
    char stringpool_str807[sizeof("DIMENSION_ALIGNED")];
    char stringpool_str811[sizeof("ASSOCACTION")];
    char stringpool_str812[sizeof("BLOCKLOOKUPACTION")];
    char stringpool_str813[sizeof("NAVISWORKSMODELDEF")];
    char stringpool_str815[sizeof("ACSH_EXTRUSION_CLASS")];
    char stringpool_str819[sizeof("ASSOCNETWORKSURFACEACTIONBODY")];
    char stringpool_str825[sizeof("FCFOBJECTCONTEXTDATA")];
    char stringpool_str837[sizeof("BLOCK_HEADER")];
    char stringpool_str853[sizeof("ACMECOMMANDHISTORY")];
    char stringpool_str905[sizeof("MOTIONPATH")];
    char stringpool_str910[sizeof("EXTRUDEDSURFACE")];
    char stringpool_str932[sizeof("LARGE_RADIAL_DIMENSION")];
    char stringpool_str936[sizeof("LAYER_INDEX")];
    char stringpool_str950[sizeof("BLOCKFLIPACTION")];
    char stringpool_str964[sizeof("CURVEPATH")];
    char stringpool_str981[sizeof("UCS_CONTROL")];
    char stringpool_str985[sizeof("VX_TABLE_RECORD")];
    char stringpool_str986[sizeof("WIPEOUTVARIABLES")];
    char stringpool_str1001[sizeof("DIMENSION_ANG2LN")];
    char stringpool_str1020[sizeof("VX_CONTROL")];
    char stringpool_str1106[sizeof("EVALUATION_GRAPH")];
    char stringpool_str1111[sizeof("ENDBLK")];
    char stringpool_str1133[sizeof("UNDERLAYDEFINITION")];
    char stringpool_str1136[sizeof("VERTEX_MESH")];
    char stringpool_str1182[sizeof("ASSOCNETWORK")];
    char stringpool_str1246[sizeof("NURBSURFACE")];
    char stringpool_str1301[sizeof("UNKNOWN_ENT")];
    char stringpool_str1331[sizeof("UNKNOWN_OBJ")];
  };
static const struct stringpool_t stringpool_contents =
  {
    "TEXT",
    "STYLE",
    "TABLE",
    "SPLINE",
    "RTEXT",
    "TRACE",
    "RAY",
    "LTYPE",
    "ASSOCARRAYACTIONBODY",
    "LAYOUT",
    "ASSOCARRAYMODIFYACTIONBODY",
    "ELLIPSE",
    "ASSOCARRAYPATHPARAMETERS",
    "ASSOCARRAYPOLARPARAMETERS",
    "ASSOCARRAYMODIFYPARAMETERS",
    "ASSOCARRAYRECTANGULARPARAMETERS",
    "ASSOCPERSSUBENTMANAGER",
    "LAYER",
    "PLANESURFACE",
    "TABLESTYLE",
    "ATTRIB",
    "ASSOCPLANESURFACEACTIONBODY",
    "SCALE",
    "POINT",
    "LEADER",
    "MTEXT",
    "BLOCKPROPERTIESTABLEGRIP",
    "BLOCKPROPERTIESTABLE",
    "ARC",
    "CAMERA",
    "ACSH_TORUS_CLASS",
    "BODY",
    "SECTION_SETTINGS",
    "LIGHT",
    "LINE",
    "SPATIAL_FILTER",
    "MLINE",
    "ACSH_BOOLEAN_CLASS",
    "SECTION_MANAGER",
    "GEODATA",
    "BLOCKBASEPOINTPARAMETER",
    "GROUP",
    "MLEADERSTYLE",
    "TABLEGEOMETRY",
    "ASSOCRESTOREENTITYSTATEACTIONBODY",
    "BLOCKRADIALCONSTRAINTPARAMETER",
    "RENDERENTRY",
    "LIGHTLIST",
    "APPID",
    "CIRCLE",
    "LEADEROBJECTCONTEXTDATA",
    "3DFACE",
    "TABLECONTENT",
    "IMAGE",
    "BLOCKPARAMDEPENDENCYBODY",
    "RASTERVARIABLES",
    "BLOCKPOLARGRIP",
    "MLINESTYLE",
    "ACSH_PYRAMID_CLASS",
    "ACSH_BOX_CLASS",
    "POINTPARAMETERENTITY",
    "MINSERT",
    "SHAPE",
    "LINEARPARAMETERENTITY",
    "ASSOCLOFTEDSURFACEACTIONBODY",
    "ACSH_SPHERE_CLASS",
    "MENTALRAYRENDERSETTINGS",
    "BLOCKLINEARGRIP",
    "RENDERGLOBAL",
    "BLOCKPOLARPARAMETER",
    "VPORT",
    "RENDERENVIRONMENT",
    "BASEPOINTPARAMETERENTITY",
    "ASSOCSWEPTSURFACEACTIONBODY",
    "BLOCKLINEARPARAMETER",
    "PERSUBENTMGR",
    "ALIGNMENTPARAMETERENTITY",
    "SOLID",
    "ACMESCOPE",
    "BLOCKLINEARCONSTRAINTPARAMETER",
    "ASSOCOFFSETSURFACEACTIONBODY",
    "RENDERSETTINGS",
    "OBJECT_PTR",
    "TEXTOBJECTCONTEXTDATA",
    "TOLERANCE",
    "CELLSTYLEMAP",
    "ASSOCVARIABLE",
    "DATATABLE",
    "MESH",
    "FLIPPARAMETERENTITY",
    "ACSH_SWEEP_CLASS",
    "DBCOLOR",
    "ORDDIMOBJECTCONTEXTDATA",
    "ASSOCOSNAPPOINTREFACTIONPARAM",
    "ASSOCEDGECHAMFERACTIONBODY",
    "ROTATIONPARAMETERENTITY",
    "ASSOCGEOMDEPENDENCY",
    "SWEPTSURFACE",
    "BLOCKDIAMETRICCONSTRAINTPARAMETER",
    "MATERIAL",
    "FIELDLIST",
    "SEQEND",
    "POINTCLOUDCOLORMAP",
    "ASSOCFILLETSURFACEACTIONBODY",
    "ASSOCEDGEACTIONPARAM",
    "OLEFRAME",
    "BLOCKVISIBILITYGRIP",
    "POINTCLOUDDEF_REACTOR",
    "PLACEHOLDER",
    "ASSOCVALUEDEPENDENCY",
    "BLOCKANGULARCONSTRAINTPARAMETER",
    "BLOCKHORIZONTALCONSTRAINTPARAMETER",
    "DICTIONARY",
    "LAYERFILTER",
    "ASSOCVERTEXACTIONPARAM",
    "BLKREFOBJECTCONTEXTDATA",
    "ARCALIGNEDTEXT",
    "DICTIONARYWDFLT",
    "BLOCKVISIBILITYPARAMETER",
    "ASSOCREVOLVEDSURFACEACTIONBODY",
    "ACSH_HISTORY_CLASS",
    "POLYLINE_PFACE",
    "ACSH_WEDGE_CLASS",
    "ACSH_FILLET_CLASS",
    "DICTIONARYVAR",
    "SECTIONVIEWSTYLE",
    "ACSH_CHAMFER_CLASS",
    "HATCH",
    "ATTDEF",
    "3DSOLID",
    "ASSOCTRIMSURFACEACTIONBODY",
    "ASSOC3POINTANGULARDIMACTIONBODY",
    "CSACDOCUMENTOPTIONS",
    "DYNAMICBLOCKPROXYNODE",
    "ASSOCBLENDSURFACEACTIONBODY",
    "ASSOCEDGEFILLETACTIONBODY",
    "ACSH_REVOLVE_CLASS",
    "FIELD",
    "ASSOCROTATEDDIMACTIONBODY",
    "DYNAMICBLOCKPURGEPREVENTER",
    "BLOCKVERTICALCONSTRAINTPARAMETER",
    "DIMSTYLE",
    "RAPIDRTRENDERSETTINGS",
    "XLINE",
    "INSERT",
    "ANNOTSCALEOBJECTCONTEXTDATA",
    "UCS",
    "BLOCKSTRETCHACTION",
    "BLOCKARRAYACTION",
    "IDBUFFER",
    "RADIMLGOBJECTCONTEXTDATA",
    "SECTIONOBJECT",
    "BLOCKPOINTPARAMETER",
    "POINTCLOUD",
    "ASSOCMLEADERACTIONBODY",
    "DIMASSOC",
    "BLOCK",
    "SORTENTSTABLE",
    "ASSOCFACEACTIONPARAM",
    "BLOCKROTATIONGRIP",
    "BLOCKSCALEACTION",
    "ASSOCPOINTREFACTIONPARAM",
    "ASSOCORDINATEDIMACTIONBODY",
    "STYLE_CONTROL",
    "BLOCKLOOKUPGRIP",
    "APPID_CONTROL",
    "IMAGEDEF_REACTOR",
    "BLOCKROTATIONPARAMETER",
    "POINTCLOUDDEF",
    "ASSOCPATHACTIONPARAM",
    "OLE2FRAME",
    "BLOCKLOOKUPPARAMETER",
    "LTYPE_CONTROL",
    "MLEADEROBJECTCONTEXTDATA",
    "POLYLINE_3D",
    "DUMMY",
    "LONG_TRANSACTION",
    "VIEW_CONTROL",
    "LAYER_CONTROL",
    "POLYLINE_2D",
    "PROXY_OBJECT",
    "TVDEVICEPROPERTIES",
    "DIMSTYLE_CONTROL",
    "LAYOUTPRINTCONFIG",
    "ASSOCDIMDEPENDENCYBODY",
    "BLOCK_CONTROL",
    "BLOCKPOLARSTRETCHACTION",
    "BLOCKREPRESENTATION",
    "ASSOC2DCONSTRAINTGROUP",
    "ANGDIMOBJECTCONTEXTDATA",
    "MULTILEADER",
    "ACMESTATEMGR",
    "ASSOCASMBODYACTIONPARAM",
    "VIEW",
    "ASSOCACTIONPARAM",
    "CONTEXTDATAMANAGER",
    "HELIX",
    "MTEXTATTRIBUTEOBJECTCONTEXTDATA",
    "XRECORD",
    "BACKGROUND",
    "ASSOCPATCHSURFACEACTIONBODY",
    "BLOCKGRIPLOCATIONCOMPONENT",
    "BLOCKXYPARAMETER",
    "RADIMOBJECTCONTEXTDATA",
    "ACSH_CYLINDER_CLASS",
    "GEOMAPIMAGE",
    "XYPARAMETERENTITY",
    "GEOPOSITIONMARKER",
    "ASSOCDEPENDENCY",
    "ALDIMOBJECTCONTEXTDATA",
    "PROXY_ENTITY",
    "ASSOCCOMPOUNDACTIONPARAM",
    "IMAGEDEF",
    "POLYLINE_MESH",
    "REVOLVEDSURFACE",
    "BLOCKFLIPPARAMETER",
    "POINTPATH",
    "MPOLYGON",
    "BLOCKUSERPARAMETER",
    "MTEXTOBJECTCONTEXTDATA",
    "ASSOCOBJECTACTIONPARAM",
    "ARC_DIMENSION",
    "LWPOLYLINE",
    "ACSH_CONE_CLASS",
    "DATALINK",
    "ACSH_LOFT_CLASS",
    "DIMENSION_ANG3PT",
    "NAVISWORKSMODEL",
    "DIMENSION_RADIUS",
    "DIMENSION_ORDINATE",
    "LOFTEDSURFACE",
    "VPORT_CONTROL",
    "DIMENSION_LINEAR",
    "POINTCLOUDEX",
    "DIMENSION_DIAMETER",
    "POINTCLOUDDEFEX",
    "POINTCLOUDDEF_REACTOR_EX",
    "WIPEOUT",
    "SUN",
    "REGION",
    "VERTEX_PFACE",
    "BLOCKFLIPGRIP",
    "BLOCKXYGRIP",
    "VERTEX_PFACE_FACE",
    "ACSH_BREP_CLASS",
    "VBA_PROJECT",
    "ASSOCALIGNEDDIMACTIONBODY",
    "VISIBILITYGRIPENTITY",
    "VISUALSTYLE",
    "VIEWPORT",
    "VISIBILITYPARAMETERENTITY",
    "ASSOCEXTENDSURFACEACTIONBODY",
    "SPATIAL_INDEX",
    "PLOTSETTINGS",
    "VERTEX_3D",
    "VERTEX_2D",
    "ASSOCEXTRUDEDSURFACEACTIONBODY",
    "SUNSTUDY",
    "BLOCKMOVEACTION",
    "BLOCKALIGNMENTGRIP",
    "UNDERLAY",
    "DMDIMOBJECTCONTEXTDATA",
    "BLOCKROTATEACTION",
    "BLOCKALIGNMENTPARAMETER",
    "DETAILVIEWSTYLE",
    "INDEX",
    "BLOCKALIGNEDCONSTRAINTPARAMETER",
    "DIMENSION_ALIGNED",
    "ASSOCACTION",
    "BLOCKLOOKUPACTION",
    "NAVISWORKSMODELDEF",
    "ACSH_EXTRUSION_CLASS",
    "ASSOCNETWORKSURFACEACTIONBODY",
    "FCFOBJECTCONTEXTDATA",
    "BLOCK_HEADER",
    "ACMECOMMANDHISTORY",
    "MOTIONPATH",
    "EXTRUDEDSURFACE",
    "LARGE_RADIAL_DIMENSION",
    "LAYER_INDEX",
    "BLOCKFLIPACTION",
    "CURVEPATH",
    "UCS_CONTROL",
    "VX_TABLE_RECORD",
    "WIPEOUTVARIABLES",
    "DIMENSION_ANG2LN",
    "VX_CONTROL",
    "EVALUATION_GRAPH",
    "ENDBLK",
    "UNDERLAYDEFINITION",
    "VERTEX_MESH",
    "ASSOCNETWORK",
    "NURBSURFACE",
    "UNKNOWN_ENT",
    "UNKNOWN_OBJ"
  };
#define stringpool ((const char *) &stringpool_contents)
const struct _dwg_dxfname *
in_word_set (register const char *str, register size_t len)
{
  static const struct _dwg_dxfname wordlist[] =
    {
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 109 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str9,                      "TEXT",                       DWG_TYPE_TEXT,	1},
      {-1}, {-1}, {-1}, {-1}, {-1},
#line 314 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str15,                            "STYLE",                             DWG_TYPE_STYLE,	0},
      {-1}, {-1}, {-1}, {-1},
#line 108 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str20,                     "ACAD_TABLE",                 DWG_TYPE_TABLE,	1},
#line 106 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str21,                    "SPLINE",                     DWG_TYPE_SPLINE,	1},
      {-1}, {-1}, {-1},
#line 101 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str25,                     "RTEXT",                      DWG_TYPE_RTEXT,	1},
      {-1}, {-1}, {-1}, {-1},
#line 111 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str30,                     "TRACE",                      DWG_TYPE_TRACE,	1},
      {-1}, {-1},
#line 97 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str33,                       "RAY",                        DWG_TYPE_RAY,	1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1},
#line 276 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str45,                            "LTYPE",                             DWG_TYPE_LTYPE,	0},
      {-1}, {-1}, {-1}, {-1},
#line 155 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str50,             "ACDBASSOCARRAYACTIONBODY",          DWG_TYPE_ASSOCARRAYACTIONBODY,	0},
#line 271 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str51,                           "LAYOUT",                            DWG_TYPE_LAYOUT,	0},
      {-1}, {-1}, {-1}, {-1},
#line 156 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str56,       "ACDBASSOCARRAYMODIFYACTIONBODY",    DWG_TYPE_ASSOCARRAYMODIFYACTIONBODY,	0},
#line 61 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str57,                   "ELLIPSE",                    DWG_TYPE_ELLIPSE,	1},
      {-1},
#line 158 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str59,         "ACDBASSOCARRAYPATHPARAMETERS",      DWG_TYPE_ASSOCARRAYPATHPARAMETERS,	0},
#line 159 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str60,        "ACDBASSOCARRAYPOLARPARAMETERS",     DWG_TYPE_ASSOCARRAYPOLARPARAMETERS,	0},
#line 157 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str61,       "ACDBASSOCARRAYMODIFYPARAMETERS",    DWG_TYPE_ASSOCARRAYMODIFYPARAMETERS,	0},
      {-1}, {-1}, {-1}, {-1},
#line 160 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str66,  "ACDBASSOCARRAYRECTANGULARPARAMETERS",  DWG_TYPE_ASSOCARRAYRECTANGULARPARAMETERS,	0},
#line 184 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str67,           "ACDBASSOCPERSSUBENTMANAGER",        DWG_TYPE_ASSOCPERSSUBENTMANAGER,	0},
      {-1}, {-1},
#line 267 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str70,                            "LAYER",                             DWG_TYPE_LAYER,	0},
      {-1},
#line 87 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str72,              "PLANESURFACE",               DWG_TYPE_PLANESURFACE,	1},
      {-1}, {-1},
#line 320 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str75,                       "TABLESTYLE",                        DWG_TYPE_TABLESTYLE,	0},
#line 48 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str76,                    "ATTRIB",                     DWG_TYPE_ATTRIB,	1},
#line 185 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str77,      "ACDBASSOCPLANESURFACEACTIONBODY",   DWG_TYPE_ASSOCPLANESURFACEACTIONBODY,	0},
      {-1}, {-1},
#line 307 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str80,                            "SCALE",                             DWG_TYPE_SCALE,	0},
      {-1}, {-1}, {-1}, {-1},
#line 88 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str85,                     "POINT",                      DWG_TYPE_POINT,	1},
#line 71 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str86,                    "LEADER",                     DWG_TYPE_LEADER,	1},
      {-1}, {-1}, {-1},
#line 81 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str90,                     "MTEXT",                      DWG_TYPE_MTEXT,	1},
      {-1}, {-1}, {-1},
#line 222 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str94,         "BLOCKPROPERTIESTABLEGRIP",          DWG_TYPE_BLOCKPROPERTIESTABLEGRIP,	0},
#line 221 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str95,             "BLOCKPROPERTIESTABLE",              DWG_TYPE_BLOCKPROPERTIESTABLE,	0},
      {-1}, {-1},
#line 44 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str98,                       "ARC",                        DWG_TYPE_ARC,	1},
      {-1}, {-1},
#line 52 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str101,                    "CAMERA",                     DWG_TYPE_CAMERA,	1},
      {-1}, {-1}, {-1}, {-1},
#line 143 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str106,                 "ACSH_TORUS_CLASS",                  DWG_TYPE_ACSH_TORUS_CLASS,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 51 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str114,                      "BODY",                       DWG_TYPE_BODY,	1},
      {-1},
#line 310 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str116,                 "SECTION_SETTINGS",                  DWG_TYPE_SECTION_SETTINGS,	0},
      {-1}, {-1}, {-1},
#line 72 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str120,                     "LIGHT",                      DWG_TYPE_LIGHT,	1},
      {-1}, {-1}, {-1},
#line 73 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str124,                      "LINE",                       DWG_TYPE_LINE,	1},
      {-1}, {-1}, {-1}, {-1},
#line 312 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str129,                   "SPATIAL_FILTER",                    DWG_TYPE_SPATIAL_FILTER,	0},
#line 79 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str130,                     "MLINE",                      DWG_TYPE_MLINE,	1},
      {-1}, {-1},
#line 129 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str133,               "ACSH_BOOLEAN_CLASS",                DWG_TYPE_ACSH_BOOLEAN_CLASS,	0},
      {-1},
#line 309 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str135,                  "SECTION_MANAGER",                   DWG_TYPE_SECTION_MANAGER,	0},
      {-1},
#line 260 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str137,                          "GEODATA",                           DWG_TYPE_GEODATA,	0},
#line 202 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str138,          "BLOCKBASEPOINTPARAMETER",           DWG_TYPE_BLOCKBASEPOINTPARAMETER,	0},
      {-1},
#line 262 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str140,                            "GROUP",                             DWG_TYPE_GROUP,	0},
      {-1},
#line 281 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str142,                     "MLEADERSTYLE",                      DWG_TYPE_MLEADERSTYLE,	0},
#line 319 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str143,                    "TABLEGEOMETRY",                     DWG_TYPE_TABLEGEOMETRY,	0},
      {-1}, {-1}, {-1}, {-1},
#line 187 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str148, "ACDBASSOCRESTOREENTITYSTATEACTIONBODY",  DWG_TYPE_ASSOCRESTOREENTITYSTATEACTIONBODY,	0},
      {-1},
#line 223 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str150,   "BLOCKRADIALCONSTRAINTPARAMETER",    DWG_TYPE_BLOCKRADIALCONSTRAINTPARAMETER,	0},
      {-1}, {-1}, {-1}, {-1}, {-1},
#line 303 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str156,                      "RENDERENTRY",                       DWG_TYPE_RENDERENTRY,	0},
      {-1}, {-1},
#line 274 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str159,                        "LIGHTLIST",                         DWG_TYPE_LIGHTLIST,	0},
#line 148 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str160,                            "APPID",                             DWG_TYPE_APPID,	0},
#line 53 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str161,                    "CIRCLE",                     DWG_TYPE_CIRCLE,	1},
      {-1},
#line 273 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str163,          "ACDB_LEADEROBJECTCONTEXTDATA_CLASS",  DWG_TYPE_LEADEROBJECTCONTEXTDATA,	0},
      {-1}, {-1},
#line 41 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str166,                    "3DFACE",                     DWG_TYPE__3DFACE,	1},
      {-1}, {-1}, {-1}, {-1}, {-1},
#line 318 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str172,                     "TABLE",                             DWG_TYPE_TABLECONTENT,	0},
      {-1}, {-1},
#line 68 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str175,                     "IMAGE",                      DWG_TYPE_IMAGE,	1},
      {-1}, {-1}, {-1},
#line 216 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str179,         "BLOCKPARAMDEPENDENCYBODY",          DWG_TYPE_BLOCKPARAMDEPENDENCYBODY,	0},
#line 302 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str180,                  "RASTERVARIABLES",                   DWG_TYPE_RASTERVARIABLES,	0},
      {-1}, {-1}, {-1},
#line 218 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str184,                   "BLOCKPOLARGRIP",                    DWG_TYPE_BLOCKPOLARGRIP,	0},
#line 282 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str185,                       "MLINESTYLE",                        DWG_TYPE_MLINESTYLE,	0},
      {-1}, {-1},
#line 139 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str188,               "ACSH_PYRAMID_CLASS",                DWG_TYPE_ACSH_PYRAMID_CLASS,	0},
#line 130 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str189,                   "ACSH_BOX_CLASS",                    DWG_TYPE_ACSH_BOX_CLASS,	0},
#line 91 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str190,      "POINTPARAMETERENTITY",       DWG_TYPE_POINTPARAMETERENTITY,	1},
      {-1},
#line 78 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str192,                   "MINSERT",                    DWG_TYPE_MINSERT,	1},
      {-1}, {-1},
#line 104 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str195,                     "SHAPE",                      DWG_TYPE_SHAPE,	1},
#line 74 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str196,     "LINEARPARAMETERENTITY",      DWG_TYPE_LINEARPARAMETERENTITY,	1},
      {-1},
#line 174 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str198,     "ACDBASSOCLOFTEDSURFACEACTIONBODY",  DWG_TYPE_ASSOCLOFTEDSURFACEACTIONBODY,	0},
      {-1}, {-1}, {-1},
#line 141 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str202,                "ACSH_SPHERE_CLASS",                 DWG_TYPE_ACSH_SPHERE_CLASS,	0},
#line 279 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str203,          "MENTALRAYRENDERSETTINGS",           DWG_TYPE_MENTALRAYRENDERSETTINGS,	0},
      {-1},
#line 210 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str205,                  "BLOCKLINEARGRIP",                   DWG_TYPE_BLOCKLINEARGRIP,	0},
      {-1},
#line 305 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str207,                     "RENDERGLOBAL",                      DWG_TYPE_RENDERGLOBAL,	0},
      {-1},
#line 219 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str209,              "BLOCKPOLARPARAMETER",               DWG_TYPE_BLOCKPOLARPARAMETER,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1},
#line 331 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str220,                            "VPORT",                             DWG_TYPE_VPORT,	0},
      {-1},
#line 304 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str222,                "RENDERENVIRONMENT",                 DWG_TYPE_RENDERENVIRONMENT,	0},
      {-1},
#line 49 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str224,  "BASEPOINTPARAMETERENTITY",   DWG_TYPE_BASEPOINTPARAMETERENTITY,	1},
      {-1}, {-1},
#line 190 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str227,      "ACDBASSOCSWEPTSURFACEACTIONBODY",   DWG_TYPE_ASSOCSWEPTSURFACEACTIONBODY,	0},
      {-1}, {-1},
#line 211 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str230,             "BLOCKLINEARPARAMETER",              DWG_TYPE_BLOCKLINEARPARAMETER,	0},
      {-1},
#line 289 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str232,                     "ACDBPERSSUBENTMANAGER",             DWG_TYPE_PERSUBENTMGR,	0},
      {-1},
#line 43 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str234,  "ALIGNMENTPARAMETERENTITY",   DWG_TYPE_ALIGNMENTPARAMETERENTITY,	1},
#line 105 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str235,                     "SOLID",                      DWG_TYPE_SOLID,	1},
      {-1}, {-1}, {-1},
#line 127 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str239,                        "ACMESCOPE",                         DWG_TYPE_ACMESCOPE,	0},
#line 209 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str240,   "BLOCKLINEARCONSTRAINTPARAMETER",    DWG_TYPE_BLOCKLINEARCONSTRAINTPARAMETER,	0},
      {-1}, {-1},
#line 179 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str243,     "ACDBASSOCOFFSETSURFACEACTIONBODY",  DWG_TYPE_ASSOCOFFSETSURFACEACTIONBODY,	0},
#line 306 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str244,                   "RENDERSETTINGS",                    DWG_TYPE_RENDERSETTINGS,	0},
#line 287 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str245,                       "OBJECT_PTR",                        DWG_TYPE_OBJECT_PTR,	0},
#line 321 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str246,            "ACDB_TEXTOBJECTCONTEXTDATA_CLASS",  DWG_TYPE_TEXTOBJECTCONTEXTDATA,	0},
      {-1}, {-1},
#line 110 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str249,                 "TOLERANCE",                  DWG_TYPE_TOLERANCE,	1},
      {-1}, {-1},
#line 238 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str252,                     "CELLSTYLEMAP",                      DWG_TYPE_CELLSTYLEMAP,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1},
#line 193 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str263,                    "ACDBASSOCVARIABLE",                 DWG_TYPE_ASSOCVARIABLE,	0},
#line 243 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str264,                        "DATATABLE",                         DWG_TYPE_DATATABLE,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 77 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str274,                      "MESH",                       DWG_TYPE_MESH,	1},
      {-1}, {-1}, {-1}, {-1},
#line 64 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str279,       "FLIPPARAMETERENTITY",        DWG_TYPE_FLIPPARAMETERENTITY,	1},
      {-1},
#line 142 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str281,                 "ACSH_SWEEP_CLASS",                  DWG_TYPE_ACSH_SWEEP_CLASS,	0},
#line 244 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str282,                          "DBCOLOR",                           DWG_TYPE_DBCOLOR,	0},
      {-1}, {-1}, {-1}, {-1}, {-1},
#line 288 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str288,          "ACDB_ORDDIMOBJECTCONTEXTDATA_CLASS",  DWG_TYPE_ORDDIMOBJECTCONTEXTDATA,	0},
#line 181 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str289,    "ACDBASSOCOSNAPPOINTREFACTIONPARAM",  DWG_TYPE_ASSOCOSNAPPOINTREFACTIONPARAM,	0},
      {-1},
#line 167 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str291,       "ACDBASSOCEDGECHAMFERACTIONBODY",    DWG_TYPE_ASSOCEDGECHAMFERACTIONBODY,	0},
      {-1},
#line 100 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str293,   "ROTATIONPARAMETERENTITY",    DWG_TYPE_ROTATIONPARAMETERENTITY,	1},
#line 173 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str294,              "ACDBASSOCGEOMDEPENDENCY",           DWG_TYPE_ASSOCGEOMDEPENDENCY,	0},
      {-1}, {-1},
#line 107 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str297,              "SWEPTSURFACE",               DWG_TYPE_SWEPTSURFACE,	1},
#line 203 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str298, "BLOCKDIAMETRICCONSTRAINTPARAMETER",  DWG_TYPE_BLOCKDIAMETRICCONSTRAINTPARAMETER,	0},
      {-1}, {-1}, {-1}, {-1},
#line 278 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str303,                         "MATERIAL",                          DWG_TYPE_MATERIAL,	0},
#line 259 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str304,                        "FIELDLIST",                         DWG_TYPE_FIELDLIST,	0},
      {-1},
#line 103 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str306,                    "SEQEND",                     DWG_TYPE_SEQEND,	1},
      {-1},
#line 292 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str308,               "ACDBPOINTCLOUDCOLORMAP",            DWG_TYPE_POINTCLOUDCOLORMAP,	0},
      {-1}, {-1}, {-1}, {-1},
#line 172 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str313,     "ACDBASSOCFILLETSURFACEACTIONBODY",  DWG_TYPE_ASSOCFILLETSURFACEACTIONBODY,	0},
      {-1},
#line 166 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str315,             "ACDBASSOCEDGEACTIONPARAM",          DWG_TYPE_ASSOCEDGEACTIONPARAM,	0},
      {-1}, {-1},
#line 86 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str318,                  "OLEFRAME",                   DWG_TYPE_OLEFRAME,	1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1},
#line 232 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str329,              "BLOCKVISIBILITYGRIP",               DWG_TYPE_BLOCKVISIBILITYGRIP,	0},
      {-1},
#line 295 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str331,            "ACDBPOINTCLOUDDEF_REACTOR",         DWG_TYPE_POINTCLOUDDEF_REACTOR,	0},
      {-1}, {-1}, {-1}, {-1},
#line 290 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str336,                      "ACDBPLACEHOLDER",                   DWG_TYPE_PLACEHOLDER,	0},
      {-1}, {-1}, {-1},
#line 192 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str340,             "ACDBASSOCVALUEDEPENDENCY",          DWG_TYPE_ASSOCVALUEDEPENDENCY,	0},
#line 200 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str341,  "BLOCKANGULARCONSTRAINTPARAMETER",   DWG_TYPE_BLOCKANGULARCONSTRAINTPARAMETER,	0},
      {-1}, {-1},
#line 208 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str344, "BLOCKHORIZONTALCONSTRAINTPARAMETER",  DWG_TYPE_BLOCKHORIZONTALCONSTRAINTPARAMETER,	0},
#line 246 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str345,                       "DICTIONARY",                        DWG_TYPE_DICTIONARY,	0},
#line 268 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str346,                      "LAYERFILTER",                       DWG_TYPE_LAYERFILTER,	0},
#line 194 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str347,           "ACDBASSOCVERTEXACTIONPARAM",        DWG_TYPE_ASSOCVERTEXACTIONPARAM,	0},
#line 196 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str348,          "ACDB_BLKREFOBJECTCONTEXTDATA_CLASS",  DWG_TYPE_BLKREFOBJECTCONTEXTDATA,	0},
#line 45 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str349,            "ARCALIGNEDTEXT",             DWG_TYPE_ARCALIGNEDTEXT,	1},
#line 248 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str350,                  "ACDBDICTIONARYWDFLT",               DWG_TYPE_DICTIONARYWDFLT,	0},
      {-1}, {-1}, {-1},
#line 233 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str354,         "BLOCKVISIBILITYPARAMETER",          DWG_TYPE_BLOCKVISIBILITYPARAMETER,	0},
#line 188 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str355,   "ACDBASSOCREVOLVEDSURFACEACTIONBODY",  DWG_TYPE_ASSOCREVOLVEDSURFACEACTIONBODY,	0},
      {-1}, {-1},
#line 137 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str358,               "ACSH_HISTORY_CLASS",                DWG_TYPE_ACSH_HISTORY_CLASS,	0},
#line 95 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str359,            "POLYLINE",                   DWG_TYPE_POLYLINE_PFACE,	1},
      {-1},
#line 144 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str361,                 "ACSH_WEDGE_CLASS",                  DWG_TYPE_ACSH_WEDGE_CLASS,	0},
      {-1}, {-1}, {-1}, {-1}, {-1},
#line 136 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str367,                "ACSH_FILLET_CLASS",                 DWG_TYPE_ACSH_FILLET_CLASS,	0},
#line 247 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str368,                    "DICTIONARYVAR",                     DWG_TYPE_DICTIONARYVAR,	0},
      {-1}, {-1},
#line 308 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str371,                 "ACDBSECTIONVIEWSTYLE",              DWG_TYPE_SECTIONVIEWSTYLE,	0},
      {-1},
#line 132 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str373,               "ACSH_CHAMFER_CLASS",                DWG_TYPE_ACSH_CHAMFER_CLASS,	0},
      {-1},
#line 66 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str375,                     "HATCH",                      DWG_TYPE_HATCH,	1},
#line 47 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str376,                    "ATTDEF",                     DWG_TYPE_ATTDEF,	1},
      {-1}, {-1}, {-1}, {-1}, {-1},
#line 42 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str382,                   "3DSOLID",                    DWG_TYPE__3DSOLID,	1},
      {-1}, {-1}, {-1},
#line 191 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str386,       "ACDBASSOCTRIMSURFACEACTIONBODY",    DWG_TYPE_ASSOCTRIMSURFACEACTIONBODY,	0},
      {-1}, {-1}, {-1}, {-1},
#line 151 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str391,  "ACDBASSOC3POINTANGULARDIMACTIONBODY",  DWG_TYPE_ASSOC3POINTANGULARDIMACTIONBODY,	0},
      {-1}, {-1},
#line 240 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str394,              "CSACDOCUMENTOPTIONS",               DWG_TYPE_CSACDOCUMENTOPTIONS,	0},
      {-1},
#line 254 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str396,            "ACAD_DYNAMICBLOCKPROXYNODE",        DWG_TYPE_DYNAMICBLOCKPROXYNODE,	0},
#line 162 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str397,      "ACDBASSOCBLENDSURFACEACTIONBODY",   DWG_TYPE_ASSOCBLENDSURFACEACTIONBODY,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 168 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str405,        "ACDBASSOCEDGEFILLETACTIONBODY",     DWG_TYPE_ASSOCEDGEFILLETACTIONBODY,	0},
      {-1}, {-1},
#line 140 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str408,               "ACSH_REVOLVE_CLASS",                DWG_TYPE_ACSH_REVOLVE_CLASS,	0},
      {-1},
#line 258 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str410,                            "FIELD",                             DWG_TYPE_FIELD,	0},
      {-1}, {-1}, {-1}, {-1},
#line 189 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str415,        "ACDBASSOCROTATEDDIMACTIONBODY",     DWG_TYPE_ASSOCROTATEDDIMACTIONBODY,	0},
#line 255 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str416,       "ACDB_DYNAMICBLOCKPURGEPREVENTER_VERSION",  DWG_TYPE_DYNAMICBLOCKPURGEPREVENTER,	0},
#line 231 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str417, "BLOCKVERTICALCONSTRAINTPARAMETER",  DWG_TYPE_BLOCKVERTICALCONSTRAINTPARAMETER,	0},
#line 250 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str418,                         "DIMSTYLE",                          DWG_TYPE_DIMSTYLE,	0},
      {-1}, {-1},
#line 301 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str421,            "RAPIDRTRENDERSETTINGS",             DWG_TYPE_RAPIDRTRENDERSETTINGS,	0},
      {-1}, {-1}, {-1},
#line 123 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str425,                     "XLINE",                      DWG_TYPE_XLINE,	1},
#line 69 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str426,                    "INSERT",                     DWG_TYPE_INSERT,	1},
#line 147 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str427,      "ACDB_ANNOTSCALEOBJECTCONTEXTDATA_CLASS",  DWG_TYPE_ANNOTSCALEOBJECTCONTEXTDATA,	0},
#line 323 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str428,                              "UCS",                               DWG_TYPE_UCS,	0},
      {-1}, {-1}, {-1}, {-1},
#line 229 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str433,               "BLOCKSTRETCHACTION",                DWG_TYPE_BLOCKSTRETCHACTION,	0},
      {-1}, {-1},
#line 201 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str436,                 "BLOCKARRAYACTION",                  DWG_TYPE_BLOCKARRAYACTION,	0},
      {-1},
#line 263 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str438,                         "IDBUFFER",                          DWG_TYPE_IDBUFFER,	0},
#line 299 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str439,         "ACDB_RADIMLGOBJECTCONTEXTDATA_CLASS",  DWG_TYPE_RADIMLGOBJECTCONTEXTDATA,	0},
      {-1}, {-1}, {-1},
#line 102 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str443,             "SECTIONOBJECT",              DWG_TYPE_SECTIONOBJECT,	1},
#line 217 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str444,              "BLOCKPOINTPARAMETER",               DWG_TYPE_BLOCKPOINTPARAMETER,	0},
#line 89 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str445,                "ACDBPOINTCLOUD",             DWG_TYPE_POINTCLOUD,	1},
      {-1},
#line 175 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str447,           "ACDBASSOCMLEADERACTIONBODY",        DWG_TYPE_ASSOCMLEADERACTIONBODY,	0},
#line 249 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str448,                         "DIMASSOC",                          DWG_TYPE_DIMASSOC,	0},
      {-1},
#line 50 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str450,                     "BLOCK",                      DWG_TYPE_BLOCK,	1},
      {-1}, {-1},
#line 311 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str453,                    "SORTENTSTABLE",                     DWG_TYPE_SORTENTSTABLE,	0},
      {-1},
#line 171 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str455,             "ACDBASSOCFACEACTIONPARAM",          DWG_TYPE_ASSOCFACEACTIONPARAM,	0},
      {-1},
#line 226 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str457,                "BLOCKROTATIONGRIP",                 DWG_TYPE_BLOCKROTATIONGRIP,	0},
      {-1}, {-1}, {-1},
#line 228 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str461,                 "BLOCKSCALEACTION",                  DWG_TYPE_BLOCKSCALEACTION,	0},
      {-1}, {-1},
#line 186 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str464,         "ACDBASSOCPOINTREFACTIONPARAM",      DWG_TYPE_ASSOCPOINTREFACTIONPARAM,	0},
      {-1},
#line 180 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str466,       "ACDBASSOCORDINATEDIMACTIONBODY",    DWG_TYPE_ASSOCORDINATEDIMACTIONBODY,	0},
      {-1},
#line 315 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str468,                    "STYLE_CONTROL",                     DWG_TYPE_STYLE_CONTROL,	0},
      {-1},
#line 213 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str470,                  "BLOCKLOOKUPGRIP",                   DWG_TYPE_BLOCKLOOKUPGRIP,	0},
      {-1}, {-1},
#line 149 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str473,                    "APPID_CONTROL",                     DWG_TYPE_APPID_CONTROL,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 265 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str481,                 "IMAGEDEF_REACTOR",                  DWG_TYPE_IMAGEDEF_REACTOR,	0},
#line 227 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str482,           "BLOCKROTATIONPARAMETER",            DWG_TYPE_BLOCKROTATIONPARAMETER,	0},
#line 293 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str483,                    "ACDBPOINTCLOUDDEF",                 DWG_TYPE_POINTCLOUDDEF,	0},
      {-1},
#line 183 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str485,             "ACDBASSOCPATHACTIONPARAM",          DWG_TYPE_ASSOCPATHACTIONPARAM,	0},
      {-1}, {-1}, {-1},
#line 85 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str489,                 "OLE2FRAME",                  DWG_TYPE_OLE2FRAME,	1},
      {-1}, {-1}, {-1}, {-1}, {-1},
#line 214 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str495,             "BLOCKLOOKUPPARAMETER",              DWG_TYPE_BLOCKLOOKUPPARAMETER,	0},
      {-1}, {-1},
#line 277 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str498,                    "LTYPE_CONTROL",                     DWG_TYPE_LTYPE_CONTROL,	0},
#line 280 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str499,         "ACDB_MLEADEROBJECTCONTEXTDATA_CLASS",  DWG_TYPE_MLEADEROBJECTCONTEXTDATA,	0},
      {-1},
#line 93 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str501,               "POLYLINE",                   DWG_TYPE_POLYLINE_3D,	1},
      {-1}, {-1}, {-1},
#line 253 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str505,                            "DUMMY",                             DWG_TYPE_DUMMY,	0},
#line 275 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str506,                 "LONG_TRANSACTION",                  DWG_TYPE_LONG_TRANSACTION,	0},
#line 329 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str507,                     "VIEW_CONTROL",                      DWG_TYPE_VIEW_CONTROL,	0},
#line 269 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str508,                    "LAYER_CONTROL",                     DWG_TYPE_LAYER_CONTROL,	0},
      {-1}, {-1},
#line 92 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str511,               "POLYLINE",                   DWG_TYPE_POLYLINE_2D,	1},
      {-1}, {-1}, {-1}, {-1}, {-1},
#line 298 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str517,                     "ACAD_PROXY_OBJECT",                 DWG_TYPE_PROXY_OBJECT,	0},
#line 322 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str518,               "TVDEVICEPROPERTIES",                DWG_TYPE_TVDEVICEPROPERTIES,	0},
      {-1}, {-1},
#line 251 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str521,                 "DIMSTYLE_CONTROL",                  DWG_TYPE_DIMSTYLE_CONTROL,	0},
#line 272 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str522,                "LAYOUTPRINTCONFIG",                 DWG_TYPE_LAYOUTPRINTCONFIG,	0},
      {-1}, {-1}, {-1}, {-1},
#line 165 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str527,           "ACDBASSOCDIMDEPENDENCYBODY",        DWG_TYPE_ASSOCDIMDEPENDENCYBODY,	0},
#line 236 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str528,                    "BLOCK_CONTROL",                     DWG_TYPE_BLOCK_CONTROL,	0},
      {-1}, {-1}, {-1}, {-1},
#line 220 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str533,          "BLOCKPOLARSTRETCHACTION",           DWG_TYPE_BLOCKPOLARSTRETCHACTION,	0},
#line 224 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str534,              "ACDB_BLOCKREPRESENTATION_DATA",     DWG_TYPE_BLOCKREPRESENTATION,	0},
      {-1}, {-1},
#line 150 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str537,           "ACDBASSOC2DCONSTRAINTGROUP",        DWG_TYPE_ASSOC2DCONSTRAINTGROUP,	0},
#line 146 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str538,          "ACDB_ANGDIMOBJECTCONTEXTDATA_CLASS",  DWG_TYPE_ANGDIMOBJECTCONTEXTDATA,	0},
      {-1}, {-1},
#line 82 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str541,               "MULTILEADER",                DWG_TYPE_MULTILEADER,	1},
      {-1}, {-1}, {-1}, {-1}, {-1},
#line 128 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str547,                     "ACMESTATEMGR",                      DWG_TYPE_ACMESTATEMGR,	0},
      {-1}, {-1}, {-1}, {-1}, {-1},
#line 161 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str553,          "ACDBASSOCASMBODYACTIONPARAM",       DWG_TYPE_ASSOCASMBODYACTIONPARAM,	0},
#line 328 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str554,                             "VIEW",                              DWG_TYPE_VIEW,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 153 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str561,                 "ACDBASSOCACTIONPARAM",              DWG_TYPE_ASSOCACTIONPARAM,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 239 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str568,               "CONTEXTDATAMANAGER",                DWG_TYPE_CONTEXTDATAMANAGER,	0},
      {-1},
#line 67 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str570,                     "HELIX",                      DWG_TYPE_HELIX,	1},
#line 284 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str571,  "ACDB_MTEXTATTRIBUTEOBJECTCONTEXTDATA_CLASS",  DWG_TYPE_MTEXTATTRIBUTEOBJECTCONTEXTDATA,	0},
#line 336 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str572,                          "XRECORD",                           DWG_TYPE_XRECORD,	0},
      {-1}, {-1},
#line 195 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str575,                       "BACKGROUND",                        DWG_TYPE_BACKGROUND,	0},
      {-1},
#line 182 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str577,      "ACDBASSOCPATCHSURFACEACTIONBODY",   DWG_TYPE_ASSOCPATCHSURFACEACTIONBODY,	0},
      {-1}, {-1}, {-1},
#line 207 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str581,       "BLOCKGRIPLOCATIONCOMPONENT",        DWG_TYPE_BLOCKGRIPLOCATIONCOMPONENT,	0},
      {-1}, {-1}, {-1}, {-1},
#line 235 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str586,                 "BLOCKXYPARAMETER",                  DWG_TYPE_BLOCKXYPARAMETER,	0},
#line 300 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str587,           "ACDB_RADIMOBJECTCONTEXTDATA_CLASS",  DWG_TYPE_RADIMOBJECTCONTEXTDATA,	0},
      {-1},
#line 134 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str589,              "ACSH_CYLINDER_CLASS",               DWG_TYPE_ACSH_CYLINDER_CLASS,	0},
      {-1},
#line 261 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str591,                      "GEOMAPIMAGE",                       DWG_TYPE_GEOMAPIMAGE,	0},
#line 124 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str592,         "XYPARAMETERENTITY",          DWG_TYPE_XYPARAMETERENTITY,	1},
      {-1}, {-1}, {-1}, {-1},
#line 65 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str597,         "POSITIONMARKER",             DWG_TYPE_GEOPOSITIONMARKER,	1},
      {-1}, {-1},
#line 164 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str600,                  "ACDBASSOCDEPENDENCY",               DWG_TYPE_ASSOCDEPENDENCY,	0},
      {-1},
#line 145 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str602,           "ACDB_ALDIMOBJECTCONTEXTDATA_CLASS",  DWG_TYPE_ALDIMOBJECTCONTEXTDATA,	0},
      {-1}, {-1}, {-1}, {-1},
#line 96 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str607,              "ACAD_ENTITY_OBJECT",         DWG_TYPE_PROXY_ENTITY,	1},
      {-1},
#line 163 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str609,         "ACDBASSOCCOMPOUNDACTIONPARAM",      DWG_TYPE_ASSOCCOMPOUNDACTIONPARAM,	0},
      {-1}, {-1}, {-1},
#line 264 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str613,                         "IMAGEDEF",                          DWG_TYPE_IMAGEDEF,	0},
      {-1}, {-1}, {-1}, {-1},
#line 94 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str618,             "POLYLINE",                   DWG_TYPE_POLYLINE_MESH,	1},
      {-1},
#line 99 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str620,           "REVOLVEDSURFACE",            DWG_TYPE_REVOLVEDSURFACE,	1},
      {-1}, {-1},
#line 206 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str623,               "BLOCKFLIPPARAMETER",                DWG_TYPE_BLOCKFLIPPARAMETER,	0},
#line 297 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str624,                        "ACDBPOINTPATH",                     DWG_TYPE_POINTPATH,	0},
      {-1}, {-1}, {-1},
#line 80 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str628,                  "MPOLYGON",                   DWG_TYPE_MPOLYGON,	1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 230 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str638,               "BLOCKUSERPARAMETER",                DWG_TYPE_BLOCKUSERPARAMETER,	0},
      {-1}, {-1}, {-1},
#line 285 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str642,           "ACDB_MTEXTOBJECTCONTEXTDATA_CLASS",  DWG_TYPE_MTEXTOBJECTCONTEXTDATA,	0},
      {-1}, {-1}, {-1}, {-1},
#line 178 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str647,           "ACDBASSOCOBJECTACTIONPARAM",        DWG_TYPE_ASSOCOBJECTACTIONPARAM,	0},
#line 46 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str648,             "ARC_DIMENSION",              DWG_TYPE_ARC_DIMENSION,	1},
      {-1},
#line 76 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str650,                "LWPOLYLINE",                 DWG_TYPE_LWPOLYLINE,	1},
      {-1}, {-1}, {-1}, {-1},
#line 133 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str655,                  "ACSH_CONE_CLASS",                   DWG_TYPE_ACSH_CONE_CLASS,	0},
      {-1}, {-1},
#line 242 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str658,                         "DATALINK",                          DWG_TYPE_DATALINK,	0},
      {-1},
#line 138 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str660,                  "ACSH_LOFT_CLASS",                   DWG_TYPE_ACSH_LOFT_CLASS,	0},
#line 56 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str661,          "DIMENSION",                  DWG_TYPE_DIMENSION_ANG3PT,	1},
      {-1}, {-1}, {-1},
#line 83 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str665,           "COORDINATION_MODEL",         DWG_TYPE_NAVISWORKSMODEL,	1},
#line 60 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str666,          "DIMENSION",                  DWG_TYPE_DIMENSION_RADIUS,	1},
      {-1},
#line 59 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str668,        "DIMENSION",                  DWG_TYPE_DIMENSION_ORDINATE,	1},
      {-1}, {-1}, {-1}, {-1},
#line 75 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str673,             "LOFTEDSURFACE",              DWG_TYPE_LOFTEDSURFACE,	1},
      {-1}, {-1}, {-1}, {-1},
#line 332 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str678,                    "VPORT_CONTROL",                     DWG_TYPE_VPORT_CONTROL,	0},
      {-1}, {-1},
#line 58 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str681,          "DIMENSION",                  DWG_TYPE_DIMENSION_LINEAR,	1},
#line 90 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str682,              "ACDBPOINTCLOUDEX",           DWG_TYPE_POINTCLOUDEX,	1},
#line 57 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str683,        "DIMENSION",                  DWG_TYPE_DIMENSION_DIAMETER,	1},
      {-1},
#line 294 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str685,                  "ACDBPOINTCLOUDDEFEX",               DWG_TYPE_POINTCLOUDDEFEX,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 296 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str694,         "ACDBPOINTCLOUDDEF_REACTOR_EX",      DWG_TYPE_POINTCLOUDDEF_REACTOR_EX,	0},
      {-1}, {-1},
#line 122 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str697,                   "WIPEOUT",                    DWG_TYPE_WIPEOUT,	1},
      {-1}, {-1}, {-1}, {-1}, {-1},
#line 316 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str703,                              "SUN",                               DWG_TYPE_SUN,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 98 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str711,                    "REGION",                     DWG_TYPE_REGION,	1},
#line 117 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str712,              "VERTEX",                     DWG_TYPE_VERTEX_PFACE,	1},
#line 205 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str713,                    "BLOCKFLIPGRIP",                     DWG_TYPE_BLOCKFLIPGRIP,	0},
      {-1}, {-1},
#line 234 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str716,                      "BLOCKXYGRIP",                       DWG_TYPE_BLOCKXYGRIP,	0},
#line 118 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str717,         "VERTEX",                     DWG_TYPE_VERTEX_PFACE_FACE,	1},
      {-1}, {-1},
#line 131 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str720,                  "ACSH_BREP_CLASS",                   DWG_TYPE_ACSH_BREP_CLASS,	0},
#line 327 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str721,                      "VBA_PROJECT",                       DWG_TYPE_VBA_PROJECT,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 154 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str730,        "ACDBASSOCALIGNEDDIMACTIONBODY",     DWG_TYPE_ASSOCALIGNEDDIMACTIONBODY,	0},
      {-1}, {-1}, {-1}, {-1},
#line 120 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str735,      "VISIBILITYGRIPENTITY",       DWG_TYPE_VISIBILITYGRIPENTITY,	1},
#line 330 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str736,                      "VISUALSTYLE",                       DWG_TYPE_VISUALSTYLE,	0},
      {-1},
#line 119 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str738,                  "VIEWPORT",                   DWG_TYPE_VIEWPORT,	1},
      {-1},
#line 121 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str740, "VISIBILITYPARAMETERENTITY",  DWG_TYPE_VISIBILITYPARAMETERENTITY,	1},
      {-1}, {-1},
#line 169 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str743,     "ACDBASSOCEXTENDSURFACEACTIONBODY",  DWG_TYPE_ASSOCEXTENDSURFACEACTIONBODY,	0},
      {-1}, {-1}, {-1}, {-1},
#line 313 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str748,                    "SPATIAL_INDEX",                     DWG_TYPE_SPATIAL_INDEX,	0},
      {-1}, {-1}, {-1},
#line 291 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str752,                     "PLOTSETTINGS",                      DWG_TYPE_PLOTSETTINGS,	0},
      {-1},
#line 115 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str754,                 "VERTEX",                     DWG_TYPE_VERTEX_3D,	1},
      {-1}, {-1}, {-1}, {-1},
#line 114 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str759,                 "VERTEX",                     DWG_TYPE_VERTEX_2D,	1},
#line 170 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str760,   "ACDBASSOCEXTRUDEDSURFACEACTIONBODY",  DWG_TYPE_ASSOCEXTRUDEDSURFACEACTIONBODY,	0},
      {-1}, {-1},
#line 317 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str763,                         "SUNSTUDY",                          DWG_TYPE_SUNSTUDY,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 215 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str770,                  "BLOCKMOVEACTION",                   DWG_TYPE_BLOCKMOVEACTION,	0},
      {-1}, {-1},
#line 198 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str773,               "BLOCKALIGNMENTGRIP",                DWG_TYPE_BLOCKALIGNMENTGRIP,	0},
      {-1}, {-1}, {-1}, {-1},
#line 112 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str778,                  "UNDERLAY",                   DWG_TYPE_UNDERLAY,	1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 252 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str787,           "ACDB_DMDIMOBJECTCONTEXTDATA_CLASS",  DWG_TYPE_DMDIMOBJECTCONTEXTDATA,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 225 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str797,                "BLOCKROTATEACTION",                 DWG_TYPE_BLOCKROTATEACTION,	0},
#line 199 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str798,          "BLOCKALIGNMENTPARAMETER",           DWG_TYPE_BLOCKALIGNMENTPARAMETER,	0},
      {-1},
#line 245 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str800,                  "ACDBDETAILVIEWSTYLE",               DWG_TYPE_DETAILVIEWSTYLE,	0},
      {-1}, {-1}, {-1}, {-1},
#line 266 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str805,                            "INDEX",                             DWG_TYPE_INDEX,	0},
#line 197 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str806,  "BLOCKALIGNEDCONSTRAINTPARAMETER",   DWG_TYPE_BLOCKALIGNEDCONSTRAINTPARAMETER,	0},
#line 54 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str807,         "DIMENSION",                  DWG_TYPE_DIMENSION_ALIGNED,	1},
      {-1}, {-1}, {-1},
#line 152 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str811,                      "ACDBASSOCACTION",                   DWG_TYPE_ASSOCACTION,	0},
#line 212 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str812,                "BLOCKLOOKUPACTION",                 DWG_TYPE_BLOCKLOOKUPACTION,	0},
#line 286 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str813,               "ACDBNAVISWORKSMODELDEF",            DWG_TYPE_NAVISWORKSMODELDEF,	0},
      {-1},
#line 135 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str815,             "ACSH_EXTRUSION_CLASS",              DWG_TYPE_ACSH_EXTRUSION_CLASS,	0},
      {-1}, {-1}, {-1},
#line 177 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str819,    "ACDBASSOCNETWORKSURFACEACTIONBODY",  DWG_TYPE_ASSOCNETWORKSURFACEACTIONBODY,	0},
      {-1}, {-1}, {-1}, {-1}, {-1},
#line 257 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str825,             "ACDB_FCFOBJECTCONTEXTDATA_CLASS",   DWG_TYPE_FCFOBJECTCONTEXTDATA,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1},
#line 237 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str837,                     "BLOCK_HEADER",                      DWG_TYPE_BLOCK_HEADER,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 126 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str853,               "ACMECOMMANDHISTORY",                DWG_TYPE_ACMECOMMANDHISTORY,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 283 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str905,                       "MOTIONPATH",                        DWG_TYPE_MOTIONPATH,	0},
      {-1}, {-1}, {-1}, {-1},
#line 63 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str910,           "EXTRUDEDSURFACE",            DWG_TYPE_EXTRUDEDSURFACE,	1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1},
#line 70 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str932,    "LARGE_RADIAL_DIMENSION",     DWG_TYPE_LARGE_RADIAL_DIMENSION,	1},
      {-1}, {-1}, {-1},
#line 270 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str936,                      "LAYER_INDEX",                       DWG_TYPE_LAYER_INDEX,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1},
#line 204 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str950,                  "BLOCKFLIPACTION",                   DWG_TYPE_BLOCKFLIPACTION,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1},
#line 241 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str964,                        "ACDBCURVEPATH",                     DWG_TYPE_CURVEPATH,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 324 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str981,                      "UCS_CONTROL",                       DWG_TYPE_UCS_CONTROL,	0},
      {-1}, {-1}, {-1},
#line 334 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str985,                  "VX_TABLE_RECORD",                   DWG_TYPE_VX_TABLE_RECORD,	0},
#line 335 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str986,                 "WIPEOUTVARIABLES",                  DWG_TYPE_WIPEOUTVARIABLES,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1},
#line 55 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str1001,          "DIMENSION",                  DWG_TYPE_DIMENSION_ANG2LN,	1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 333 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str1020,                       "VX_CONTROL",                        DWG_TYPE_VX_CONTROL,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1},
#line 256 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str1106,                 "ACAD_EVALUATION_GRAPH",             DWG_TYPE_EVALUATION_GRAPH,	0},
      {-1}, {-1}, {-1}, {-1},
#line 62 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str1111,                    "ENDBLK",                     DWG_TYPE_ENDBLK,	1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1},
#line 325 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str1133,               "UNDERLAYDEFINITION",                DWG_TYPE_UNDERLAYDEFINITION,	0},
      {-1}, {-1},
#line 116 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str1136,               "VERTEX",                     DWG_TYPE_VERTEX_MESH,	1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 176 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str1182,                     "ACDBASSOCNETWORK",                  DWG_TYPE_ASSOCNETWORK,	0},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 84 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str1246,               "NURBSURFACE",                DWG_TYPE_NURBSURFACE,	1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
#line 113 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str1301,               "UNKNOWN_ENT",                DWG_TYPE_UNKNOWN_ENT,	1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
      {-1}, {-1},
#line 326 "src/objects.in"
      {(int)(size_t)&((struct stringpool_t *)0)->stringpool_str1331,                      "UNKNOWN_OBJ",                       DWG_TYPE_UNKNOWN_OBJ,	0}
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register unsigned int key = hash (str, len);

      if (key <= MAX_HASH_VALUE)
        {
          register int o = wordlist[key].name;
          if (o >= 0)
            {
              register const char *s = o + stringpool;

              if (*str == *s && !strcmp (str + 1, s + 1))
                return &wordlist[key];
            }
        }
    }
  return 0;
}
#line 337 "src/objects.in"


/* Find if an object name (our internal name, not anything used elsewhere)
   is defined, and return our fixed type, the public dxfname and if it's an entity. */
EXPORT int dwg_object_name (const char *const restrict name, const char **restrict dxfname,
                            Dwg_Object_Type *restrict typep, int *restrict is_entp)
{
  const struct _dwg_dxfname* result = in_word_set (name, strlen (name));
  if (result)
    {
      *dxfname = result->dxfname;
      *typep   = result->type;
      *is_entp = result->isent;
      return 1;
    }
  return 0;
}

/*
 * Local variables:
 *   c-file-style: "gnu"
 * End:
 * vim: expandtab shiftwidth=4 cinoptions='\:2=2' :
 */
