/* ex: set ro ft=c: -*- mode: c; buffer-read-only: t -*- */
// Copyright (C) 2023 Free Software Foundation, Inc.
// This file is part of LibreDWG.
// Generated by txt2h.pl.

#include <stdint.h>

static const uint16_t cptbl_iso_8859_6[] = {
  [0x0] = 242,	// size of vector
  [0x80] = 0x0080,	// 	<control>
  [0x81] = 0x0081,	// 	<control>
  [0x82] = 0x0082,	// 	<control>
  [0x83] = 0x0083,	// 	<control>
  [0x84] = 0x0084,	// 	<control>
  [0x85] = 0x0085,	// 	<control>
  [0x86] = 0x0086,	// 	<control>
  [0x87] = 0x0087,	// 	<control>
  [0x88] = 0x0088,	// 	<control>
  [0x89] = 0x0089,	// 	<control>
  [0x8A] = 0x008A,	// 	<control>
  [0x8B] = 0x008B,	// 	<control>
  [0x8C] = 0x008C,	// 	<control>
  [0x8D] = 0x008D,	// 	<control>
  [0x8E] = 0x008E,	// 	<control>
  [0x8F] = 0x008F,	// 	<control>
  [0x90] = 0x0090,	// 	<control>
  [0x91] = 0x0091,	// 	<control>
  [0x92] = 0x0092,	// 	<control>
  [0x93] = 0x0093,	// 	<control>
  [0x94] = 0x0094,	// 	<control>
  [0x95] = 0x0095,	// 	<control>
  [0x96] = 0x0096,	// 	<control>
  [0x97] = 0x0097,	// 	<control>
  [0x98] = 0x0098,	// 	<control>
  [0x99] = 0x0099,	// 	<control>
  [0x9A] = 0x009A,	// 	<control>
  [0x9B] = 0x009B,	// 	<control>
  [0x9C] = 0x009C,	// 	<control>
  [0x9D] = 0x009D,	// 	<control>
  [0x9E] = 0x009E,	// 	<control>
  [0x9F] = 0x009F,	// 	<control>
  [0xA0] = 0x00A0,	// 	NO-BREAK SPACE
  [0xA4] = 0x00A4,	// 	CURRENCY SIGN
  [0xAC] = 0x060C,	// 	ARABIC COMMA
  [0xAD] = 0x00AD,	// 	SOFT HYPHEN
  [0xBB] = 0x061B,	// 	ARABIC SEMICOLON
  [0xBF] = 0x061F,	// 	ARABIC QUESTION MARK
  [0xC1] = 0x0621,	// 	ARABIC LETTER HAMZA
  [0xC2] = 0x0622,	// 	ARABIC LETTER ALEF WITH MADDA ABOVE
  [0xC3] = 0x0623,	// 	ARABIC LETTER ALEF WITH HAMZA ABOVE
  [0xC4] = 0x0624,	// 	ARABIC LETTER WAW WITH HAMZA ABOVE
  [0xC5] = 0x0625,	// 	ARABIC LETTER ALEF WITH HAMZA BELOW
  [0xC6] = 0x0626,	// 	ARABIC LETTER YEH WITH HAMZA ABOVE
  [0xC7] = 0x0627,	// 	ARABIC LETTER ALEF
  [0xC8] = 0x0628,	// 	ARABIC LETTER BEH
  [0xC9] = 0x0629,	// 	ARABIC LETTER TEH MARBUTA
  [0xCA] = 0x062A,	// 	ARABIC LETTER TEH
  [0xCB] = 0x062B,	// 	ARABIC LETTER THEH
  [0xCC] = 0x062C,	// 	ARABIC LETTER JEEM
  [0xCD] = 0x062D,	// 	ARABIC LETTER HAH
  [0xCE] = 0x062E,	// 	ARABIC LETTER KHAH
  [0xCF] = 0x062F,	// 	ARABIC LETTER DAL
  [0xD0] = 0x0630,	// 	ARABIC LETTER THAL
  [0xD1] = 0x0631,	// 	ARABIC LETTER REH
  [0xD2] = 0x0632,	// 	ARABIC LETTER ZAIN
  [0xD3] = 0x0633,	// 	ARABIC LETTER SEEN
  [0xD4] = 0x0634,	// 	ARABIC LETTER SHEEN
  [0xD5] = 0x0635,	// 	ARABIC LETTER SAD
  [0xD6] = 0x0636,	// 	ARABIC LETTER DAD
  [0xD7] = 0x0637,	// 	ARABIC LETTER TAH
  [0xD8] = 0x0638,	// 	ARABIC LETTER ZAH
  [0xD9] = 0x0639,	// 	ARABIC LETTER AIN
  [0xDA] = 0x063A,	// 	ARABIC LETTER GHAIN
  [0xE0] = 0x0640,	// 	ARABIC TATWEEL
  [0xE1] = 0x0641,	// 	ARABIC LETTER FEH
  [0xE2] = 0x0642,	// 	ARABIC LETTER QAF
  [0xE3] = 0x0643,	// 	ARABIC LETTER KAF
  [0xE4] = 0x0644,	// 	ARABIC LETTER LAM
  [0xE5] = 0x0645,	// 	ARABIC LETTER MEEM
  [0xE6] = 0x0646,	// 	ARABIC LETTER NOON
  [0xE7] = 0x0647,	// 	ARABIC LETTER HEH
  [0xE8] = 0x0648,	// 	ARABIC LETTER WAW
  [0xE9] = 0x0649,	// 	ARABIC LETTER ALEF MAKSURA
  [0xEA] = 0x064A,	// 	ARABIC LETTER YEH
  [0xEB] = 0x064B,	// 	ARABIC FATHATAN
  [0xEC] = 0x064C,	// 	ARABIC DAMMATAN
  [0xED] = 0x064D,	// 	ARABIC KASRATAN
  [0xEE] = 0x064E,	// 	ARABIC FATHA
  [0xEF] = 0x064F,	// 	ARABIC DAMMA
  [0xF0] = 0x0650,	// 	ARABIC KASRA
  [0xF1] = 0x0651,	// 	ARABIC SHADDA
  [0xF2] = 0x0652,	// 	ARABIC SUKUN
};
#define MIN_ISO_8859_6	0
#define MAX_ISO_8859_6	242
#define MIN_ISO_8859_6_UC	0
#define MAX_ISO_8859_6_UC	242
