/* ex: set ro ft=c: -*- mode: c; buffer-read-only: t -*- */
// Copyright (C) 2023 Free Software Foundation, Inc.
// This file is part of LibreDWG.
// Generated by txt2h.pl.

#include <stdint.h>

static const uint16_t cptbl_iso_8859_8[] = {
  [0x0] = 254,	// size of vector
  [0x80] = 0x0080,	// 	<control>
  [0x81] = 0x0081,	// 	<control>
  [0x82] = 0x0082,	// 	<control>
  [0x83] = 0x0083,	// 	<control>
  [0x84] = 0x0084,	// 	<control>
  [0x85] = 0x0085,	// 	<control>
  [0x86] = 0x0086,	// 	<control>
  [0x87] = 0x0087,	// 	<control>
  [0x88] = 0x0088,	// 	<control>
  [0x89] = 0x0089,	// 	<control>
  [0x8A] = 0x008A,	// 	<control>
  [0x8B] = 0x008B,	// 	<control>
  [0x8C] = 0x008C,	// 	<control>
  [0x8D] = 0x008D,	// 	<control>
  [0x8E] = 0x008E,	// 	<control>
  [0x8F] = 0x008F,	// 	<control>
  [0x90] = 0x0090,	// 	<control>
  [0x91] = 0x0091,	// 	<control>
  [0x92] = 0x0092,	// 	<control>
  [0x93] = 0x0093,	// 	<control>
  [0x94] = 0x0094,	// 	<control>
  [0x95] = 0x0095,	// 	<control>
  [0x96] = 0x0096,	// 	<control>
  [0x97] = 0x0097,	// 	<control>
  [0x98] = 0x0098,	// 	<control>
  [0x99] = 0x0099,	// 	<control>
  [0x9A] = 0x009A,	// 	<control>
  [0x9B] = 0x009B,	// 	<control>
  [0x9C] = 0x009C,	// 	<control>
  [0x9D] = 0x009D,	// 	<control>
  [0x9E] = 0x009E,	// 	<control>
  [0x9F] = 0x009F,	// 	<control>
  [0xA0] = 0x00A0,	// 	NO-BREAK SPACE
  [0xA2] = 0x00A2,	// 	CENT SIGN
  [0xA3] = 0x00A3,	// 	POUND SIGN
  [0xA4] = 0x00A4,	// 	CURRENCY SIGN
  [0xA5] = 0x00A5,	// 	YEN SIGN
  [0xA6] = 0x00A6,	// 	BROKEN BAR
  [0xA7] = 0x00A7,	// 	SECTION SIGN
  [0xA8] = 0x00A8,	// 	DIAERESIS
  [0xA9] = 0x00A9,	// 	COPYRIGHT SIGN
  [0xAA] = 0x00D7,	// 	MULTIPLICATION SIGN
  [0xAB] = 0x00AB,	// 	LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
  [0xAC] = 0x00AC,	// 	NOT SIGN
  [0xAD] = 0x00AD,	// 	SOFT HYPHEN
  [0xAE] = 0x00AE,	// 	REGISTERED SIGN
  [0xAF] = 0x00AF,	// 	MACRON
  [0xB0] = 0x00B0,	// 	DEGREE SIGN
  [0xB1] = 0x00B1,	// 	PLUS-MINUS SIGN
  [0xB2] = 0x00B2,	// 	SUPERSCRIPT TWO
  [0xB3] = 0x00B3,	// 	SUPERSCRIPT THREE
  [0xB4] = 0x00B4,	// 	ACUTE ACCENT
  [0xB5] = 0x00B5,	// 	MICRO SIGN
  [0xB6] = 0x00B6,	// 	PILCROW SIGN
  [0xB7] = 0x00B7,	// 	MIDDLE DOT
  [0xB8] = 0x00B8,	// 	CEDILLA
  [0xB9] = 0x00B9,	// 	SUPERSCRIPT ONE
  [0xBA] = 0x00F7,	// 	DIVISION SIGN
  [0xBB] = 0x00BB,	// 	RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
  [0xBC] = 0x00BC,	// 	VULGAR FRACTION ONE QUARTER
  [0xBD] = 0x00BD,	// 	VULGAR FRACTION ONE HALF
  [0xBE] = 0x00BE,	// 	VULGAR FRACTION THREE QUARTERS
  [0xDF] = 0x2017,	// 	DOUBLE LOW LINE
  [0xE0] = 0x05D0,	// 	HEBREW LETTER ALEF
  [0xE1] = 0x05D1,	// 	HEBREW LETTER BET
  [0xE2] = 0x05D2,	// 	HEBREW LETTER GIMEL
  [0xE3] = 0x05D3,	// 	HEBREW LETTER DALET
  [0xE4] = 0x05D4,	// 	HEBREW LETTER HE
  [0xE5] = 0x05D5,	// 	HEBREW LETTER VAV
  [0xE6] = 0x05D6,	// 	HEBREW LETTER ZAYIN
  [0xE7] = 0x05D7,	// 	HEBREW LETTER HET
  [0xE8] = 0x05D8,	// 	HEBREW LETTER TET
  [0xE9] = 0x05D9,	// 	HEBREW LETTER YOD
  [0xEA] = 0x05DA,	// 	HEBREW LETTER FINAL KAF
  [0xEB] = 0x05DB,	// 	HEBREW LETTER KAF
  [0xEC] = 0x05DC,	// 	HEBREW LETTER LAMED
  [0xED] = 0x05DD,	// 	HEBREW LETTER FINAL MEM
  [0xEE] = 0x05DE,	// 	HEBREW LETTER MEM
  [0xEF] = 0x05DF,	// 	HEBREW LETTER FINAL NUN
  [0xF0] = 0x05E0,	// 	HEBREW LETTER NUN
  [0xF1] = 0x05E1,	// 	HEBREW LETTER SAMEKH
  [0xF2] = 0x05E2,	// 	HEBREW LETTER AYIN
  [0xF3] = 0x05E3,	// 	HEBREW LETTER FINAL PE
  [0xF4] = 0x05E4,	// 	HEBREW LETTER PE
  [0xF5] = 0x05E5,	// 	HEBREW LETTER FINAL TSADI
  [0xF6] = 0x05E6,	// 	HEBREW LETTER TSADI
  [0xF7] = 0x05E7,	// 	HEBREW LETTER QOF
  [0xF8] = 0x05E8,	// 	HEBREW LETTER RESH
  [0xF9] = 0x05E9,	// 	HEBREW LETTER SHIN
  [0xFA] = 0x05EA,	// 	HEBREW LETTER TAV
  [0xFD] = 0x200E,	// 	LEFT-TO-RIGHT MARK
  [0xFE] = 0x200F,	// 	RIGHT-TO-LEFT MARK
};
#define MIN_ISO_8859_8	0
#define MAX_ISO_8859_8	254
#define MIN_ISO_8859_8_UC	0
#define MAX_ISO_8859_8_UC	8215
